### ISSUE TITLE
Create Rage Report Template and Wiki

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#10]
## What

Create a v1 _Rage Report_ template and _Rage Reports_ page on the Sage Wiki for future use/reference.

## Todo

- Review Jord's [Rage Report: Summoner](https://hackmd.io/SLJNR5VoSzGlrJPN1_DnqA) doc and create an initial draft of a template
- Add the _Rage Report_ to the Sage Wiki

## Resources

- Relates to https://github.com/HausDAO/daohaus-rage/issues/9

**Comment by jordanlesich** [comment]
I'd be happy to collab on this a bit. I'll be finishing my Rage Report for TXs soon,

**Comment by jonathanprozzi** [comment]
> I'd be happy to collab on this a bit. I'll be finishing my Rage Report for TXs soon,

Would love that -- I added your existing Rage Reports to the Wiki -- https://github.com/HausDAO/daohaus-monorepo/wiki/Docs

Definitely want your thoughts on a template -- we have some ideas for an additional section but your format is great!

**Comment by earth2travis** [comment]
https://github.com/HausDAO/daohaus-monorepo/wiki/Rage

**Comment by earth2travis** [comment]
Created a page to fill out with the Rage Report Template https://github.com/HausDAO/daohaus-monorepo/wiki/Rage-Report-Template

**Comment by jonathanprozzi** [comment]
Ready for review: https://github.com/HausDAO/daohaus-monorepo/wiki/Rage-Report-Template

Also created a general Templates page where we can add template links with instructions to how/when to use: https://github.com/HausDAO/daohaus-monorepo/wiki/templates

We can refine this report as we go, but this is meant to be a starting point for folks @earth2travis

**Comment by earth2travis** [comment]
Made some minor edits and formatting changes.

Created an Issue Template https://github.com/HausDAO/daohaus-rage/blob/master/.github/ISSUE_TEMPLATE/rage-report.md in the `daohaus-rage` repo. 

Removed the Templates page as for now I think everything is included here: https://github.com/HausDAO/daohaus-monorepo/wiki/GitHub
