### ISSUE TITLE
Rage on Monorepo Rework

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#1021]
# Details

- [ ] NX vs. Workspaces - pros and cons
- [ ] Build one app and one lib
- [ ] change app framework to nx default or raw webpack?
- [ ] Explore building/publishing to npm for a library
  - UI library
- [ ] dao-data - test node library
- [ ] test usage in external app

## Criteria
- local dev - how do we manage commands - custom build, ect...
- plan for CI - running test/builds and linting on prs into develop
- plan for cd - fleek deployments in github action/workflows
- environment variables work
- a library can inherit from another and build properly - test peer dependencies
- can we use all our same linting/tsconfigs/ect...

## versioning
- out of this scope - we need planning on how this will work in more of a maintenance phase.

**Comment by earth2travis** [comment]
https://hackmd.io/UhYDfWEXTOGnwzEzJNHhbw

**Comment by earth2travis** [comment]
https://github.com/HausDAO/monorepo
