### ISSUE TITLE
Create Starter Template

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#1044]
Create design to load when our starter templates are launched

## Current

<img width="1344" alt="dao" src="https://user-images.githubusercontent.com/522182/200686151-ec734fc7-94a1-4880-bb05-aa1ba83bdbeb.png">

<img width="1344" alt="signal" src="https://user-images.githubusercontent.com/522182/200686763-f9d1a4e2-814f-4887-9adb-975b756d4449.png">

<img width="1344" alt="scoped" src="https://user-images.githubusercontent.com/522182/200688255-b062cf9e-5e00-4031-b93f-1f39514cea0c.png">

### [Create Next App](https://nextjs.org/docs/getting-started)

<img width="1344" alt="create-next-app" src="https://user-images.githubusercontent.com/522182/200687502-b90da79a-0a49-4386-9092-129d5f801fdf.png">

### [Vite](https://vitejs.dev/guide/)

<img width="1344" alt="vite" src="https://user-images.githubusercontent.com/522182/200687913-f45ef2f1-b1db-4dc3-8d75-60ca6a65c53b.png">

### [Create React App](https://reactjs.org/docs/getting-started.html)

<img width="763" alt="create-react-app" src="https://user-images.githubusercontent.com/522182/200685967-ccc49789-e446-47b9-8ca1-6deeb3eb6d19.png">

**Comment by 7helles** [comment]
Figma: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=8349%3A254876&t=fo812yktqDPSRvzx-0

- This could use the same image as the one used for Summon's success page, or if the gif seems too busy/distracting, a static image could be used instead.
- "Example Form" could go to a signal form as shown above
- Header is an H2


![Image](https://user-images.githubusercontent.com/97971946/202270243-086fe3e8-d4d9-4e71-ba37-ffcfe22e94de.png)
