### ISSUE TITLE
Add DAO Name Above Navigation

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#1045]
It can be confusing when using the Admin app to know which DAO you are currently viewing.

Add DAO name above the navigation bar on desktop and mobile views.

**Comment by 7helles** [comment]
Design notes:

- The name could be dropped in favor of just the icon on smallest breakpoints. This will also leave room for wallet error messages.
- It seems likely users would expect clicking the icon and/or name to do something; my suggestion would be to have it go to the DAO's homepage.
- Icon size: 48x48px, same height as the connect wallet button
- DAO name text size: H4
- DAO name should be centered vertically in relation to the icon; the icon should have the same top/bottom and left margins as the wallet connect button does (on the right, in the wallet connect button's case)

Figma: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6834%3A187038


![Image](https://user-images.githubusercontent.com/97971946/201432082-e12a5024-3820-41f2-991b-b316e45332c0.png)


![Image](https://user-images.githubusercontent.com/97971946/201433719-3122074f-817c-481e-b147-43ddca0e09d2.png)
