### ISSUE TITLE
[DATA] Create DAOs Table

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#108]
## Overview

This adds everything related to the data needed to display basic DAO information for the Alpha version of the "DAOs Table" in the Hub App.

## Details

The "DAOs Table" in Hub App Alpha version **doesn't** include totals, filters, and search. These can be added in a later version.

We talked about a few possible inclusions, such as:
- Possibly a `getAllDAOsByUserAddress`
  - List of DAOs user is a member of by address
  - `name` is only metadata right now
  - Can add metadata for the other fields such as `proposalCount`

@skuhlmann I'm not sure what is appropriate in scope to include for this, but wanted to get the card created for this.

## Related Issues

- The UI feature issue for this is outlined in #107 
- The Pagination issue (#106) may make sense to combine with this

## Deliverables

- DAO data fetching functions added to our data package

**Comment by skuhlmann** [comment]
https://github.com/HausDAO/daohaus-monorepo/pull/136
