### ISSUE TITLE
@daohaus/data: Support Paginated Querying

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#111]
Might be a rage 1st
- Look into potential proposal list filtering and pagination support
- Might need to be some special defined where queries we store as constants
  - ie) status filters using complex time gte/lte filters

**Comment by alexkeating** [comment]
Any pagination should support cursor pagination and avoid skip as that is not performant.

**Comment by skuhlmann** [comment]
some initial notes:
https://hackmd.io/wtDwRLeVTsepeDjeiQ0lyg?view#Pagination-notes

and reference twitter interface for inspiration
https://github.com/twitterdev/twitter-api-typescript-sdk/blob/96310a1782edcb854475e6588fc85b09bb7d7ecf/src/request.ts#L107
