### ISSUE TITLE
Epic: Proposal Detail View

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#119]
## Description

Core UI dao proposal details page.

## Use cases

A user should be able to:
- See all relevant proposal details
  - name, description, content url, proposal type, expiration date, proposer, tribute and recipient (if applicable) , proposal offering
- See proposal status
  - [see details card for status list](https://github.com/HausDAO/daohaus-monorepo/issues/115)
- See current vote totals
- See proposal lifecycle data
  - when and who proposed it, with tx link
  - when and who sponsored it w/ tx link
  - when and who cancelled it w/ tx link
  - when and who have voted, vote shares, when + tx link
  - when and who processed it w/ tx link
- See proposal action data
  - per action: target contract, function name, arguments and their values
- Act on the proposal if in certain states
  - process proposal

A connected dao share holder/delegate should be able to
- Act on the proposal if in certain states
  - if member, vote
  - if member, sponsor
- See their votes if they have voted
- Process

A proposal proposer should be able to
- Act on the proposal if in certain states
  - if proposer, cancel

## Considerations

- see [Proposal card use cases](https://github.com/HausDAO/daohaus-monorepo/issues/115), details should work in tandem with these
- User states: Not connected, connected non-member/loot holder, connected share holder

Proposal types - Priority 1
- Tribute proposal
- Tokens for shares/loot
- Shares/loot request w/out tribute
- Funding request for tokens
- Whitelist/change permissions on shaman proposal
- Change governance settings
- Disperse

Proposal types - Priority 2
- Wallet connect proposal

Proposal types - Priority 3
- Multi TX Builder

### future considerations
- how can we give dao members more confidence on what the proposal is doing?
  - transaction simulation services

## Available data fields

Proposal
- Name
- Description
- Type
- Submitted by
- Recipient (for tribute proposal we have this)
- transaction hash/etherscan link
- expiration date/time (optional)
- Status
  - un-sponsored
  - cancelled
  - in voting period
  - in grace period
  - failed
  - passed/needs execution
  - passed/executed
  - passed/failed execution
  - expired (can't be sponsored)
 - Submission date
- Details on asset transfer (ex. membership: sending in 100xdai < receive 10 shares) - for tribute proposals
- Vote distribution
- Connected shareholder's vote
  - or your delegate has
- Time to important status changes (7 mins to grace period)
- Action data
  - does any of this get surfaced on the proposal card?

**Comment by skuhlmann** [comment]
@adriennetilley 

Adding notes about some stuff I'm uncovering in baal to consider here:

1. There is no early execution on proposals anymore. We didn't note anything on that above I don't think, but it is there if referencing v2.

2. Cancelling proposals can only happen if the proposal is in the Voting Period
- I previously had assumed it had to be Unsponsored
- there is some crazy logic on who can cancel
  - shaman with gov permissions
  - the proposal sponsor (not necessarily the submitter)
  - if the sponsor's share total drop below the dao's sponsor threshold, anyone can sponsor

**Comment by skuhlmann** [comment]
3. quorumPercentage works slightly different than I had assumed. In v2 it was all about early execution with minions. not anymore.
- any proposal that has less yesVotes than the quorum percentage (percentage of total shares) will fail when being executed.

**Comment by adriennetilley** [comment]
> There is no early execution on proposals anymore. 

I had included this in the designs, so thank you for noting. Removing 

> Cancelling proposals can only happen if the proposal is in the Voting Period

Just to make sure I understand, if you make a mistake and it's not auto-sponsored you have to get someone to sponsor it before you can cancel?

> any proposal that has less yesVotes than the quorum percentage (percentage of total shares) will fail when being executed.

A few question around this:
- If it has no expiration, will it just sit there till someone tries and fails to execute it > then it's processed? 
- This might be a stupid question, but would processing this (and it failing) cost gas? I'm wondering about if they are hanging around and you want to get rid of them, but you know it will fail it might be a headache on mainnet

**Comment by skuhlmann** [comment]
> Just to make sure I understand, if you make a mistake and it's not auto-sponsored you have to get someone to sponsor it before you can cancel?

Yeah that's right.

> * If it has no expiration, will it just sit there till someone tries and fails to execute it > then it's processed?

Yeah - it would be best to push them top process it still so it can't be processed later if it somehow comes back into quorum.

> * This might be a stupid question, but would processing this (and it failing) cost gas? I'm wondering about if they are hanging around and you want to get rid of them, but you know it will fail it might be a headache on mainnet

- it will cost gas - but it also protects it from ever being processed in the future - see above.

**Comment by skuhlmann** [comment]
@adriennetilley 

the other thing I forgot about is proposals do need to be processed in order. so they shouldn't just sit around for a while.

we'll want to notify the user that a previous proposal needs processing before a new one can be.

**Comment by adriennetilley** [comment]
@skuhlmann 

Few notes/Qs:
- I'm thinking: If proposal did not met min quorum > making the button say 'process' rather than 'execute'
- 'so it can't be processed later if it somehow comes back into quorum' < how might this happen? 
- I forgot about the ordering of the proposal processing, I'll think on how that gets incorporated into the designs

**Comment by skuhlmann** [comment]
> * I'm thinking: If proposal did not met min quorum > making the button say 'process' rather than 'execute'
yeah that makes sense to me too.

> * 'so it can't be processed later if it somehow comes back into quorum' < how might this happen?
this can happen if total dao shares are lower later... if members burn shares basically.

**Comment by skuhlmann** [comment]
@adriennetilley 

hopefully does't confuse us more:

| status      | definition/considerations                                                       | entity logic        |
| ----------- | ---------------------------------------------------------------- | ------------------- |
| Unsponsored | - not self sponsored <br> - not sponsored by a member | sponsored == false |
| Cancelled | - must be in voting to cancel <br> - can only be cancelled by gov shaman, sponsor, anyone if the sponsor's share total drop below the dao's sponsor threshold | cancelled == true
| Voting | - between voting starts and ends | votingStarts < now && votingEnds > now
| Grace | - between voting ends and grace ends | votingEnds < now && graceEnds > now
| Expired | - expiration time set on proposal submission <br> - still needs to be processed for prop queue <br> - processing will not execute actions | expiration != 0 && cancelled == false && processed == false && expiration time < votingPeriod + gracePeriod + now
| Needs Processing | - defeated (no > yes) & cancelled count as processed <br> - the previous proposal must be processed (or defeated, cancelled) | now > graceEnds && yes > no && processed = false
| Passed & Executed | - yes > no <br> - meets quorum <br> - not expired <br> - processed | processed == true
| Failed | - defeated (doesn't need processing) or marked failed in processing <br> - or processed and failed due expiration or minQuorom | now > graceEnds && yes > no && meetsQuorum && cancelled == false
| Action Failed | - processing was tried but the action exectuon failed <br> - can't be re-processed |  actionFailed == true
