### ISSUE TITLE
Create Summoner Alpha UX/UI

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#12]
Figma specs:
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=3609%3A21607

**Comment by adriennetilley** [comment]
I moved transaction interactions into it's own ticket, moving this one into ready for spec

**Comment by skuhlmann** [comment]
Broken down into many new feature development cards:

https://github.com/orgs/HausDAO/projects/3/views/13
