### ISSUE TITLE
Create `Icon` Component

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#122]
# Create `<Icon/>` Component

Create a reusable Icon component that supports the icons we are using in the Pattern Library. 

Padding and margin will be adjusted in the molecule that composes this -- this component is the Icon atom only.
 
## Details

Name: `<Icon />`

### Spec Details

- Take in any SVG as a `child` as a React component or as a `path`
- Props:
  - `color` 
  - `width`
  - `height`

## Resources/Design

- [Figma Pattern Library Link](https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=23%3A410)

## Deliverable

- Code/PR including the Icon in the `haus-component` package
- Storybook story for the Icon with at least 1 demo Icon used

**Comment by jordanlesich** [comment]
React Icons are a component that already allows us to adjust width, height, and color. 

Do we need to make new component?

**Comment by skuhlmann** [comment]
note:

'output of icon should match spacing and formatting of react-icons to keep things consistent'

**Comment by 0xRowdy** [comment]
> React Icons are a component that already allows us to adjust width, height, and color.
> 
> Do we need to make a new component?

I'm wondering the same thing about this? I'm not 100% if react-icons is accessable out of the box or if we need to leverage something like https://www.radix-ui.com/docs/primitives/utilities/accessible-icon

**Comment by jonathanprozzi** [comment]
Closed by #216
