### ISSUE TITLE
Create `BlockExplorerLink` Molecule Component

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#123]
# Create `<BlockExplorerLink/>` Component

This composes the Text component for the truncated address and an  `<Icon/>` component for the External Link into the molecule.

## Details

Name: `<BlockExplorerLink />`

Molecule Structure:
- Truncated address text block and `ExternalLink` `<Icon/>`  that are aligned to follow the Figma

### Props

- `address`
  - Type: `string`
- `linkType` -- address, txHash 
  - consider restricting this with an `enum` in the TypeScript instead of a `string`
-  `network` -- coming in from the networkID
- `textColor?` -- optional text color for the truncated address, default is white
- `iconColor?` -- optional icon color, default is primary color

## Relevant Issues

- [Issue #120](https://github.com/HausDAO/daohaus-monorepo/issues/120)

## Deliverable

- Code/PR that includes the molecule and the types
- Storybook deployment

## Resources/Design

- [Figma Link](https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=4005%3A28979)

**Comment by skuhlmann** [comment]
Note:

We are going to move forward with this one with the react-icon component. We'll replace with the daohaus-ui Icon component when ready.

**Comment by jordanlesich** [comment]
This does use a link component. Didn't actually see any designs for this. I'll let design know and use a temporary primitive for now.

**Comment by jonathanprozzi** [comment]
Closed by https://github.com/HausDAO/daohaus-monorepo/pull/181 but we may want to revisit in the future if there are updated designs like you noted @jordanlesich
