### ISSUE TITLE
Create Search for the DAOs data section

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#129]
## Overview

Build out the search input component and the searching logic for the DAOs in both the Table and Grid views.

![Image](https://user-images.githubusercontent.com/9438776/175980651-f6fee1f3-57cd-48fd-abea-6f859d5993f2.png)

## User Stories

- As a connected user, I should be able to use the _Search_ as a fuzzy search across all data in both Table and Grid views.
- As a connected user, the Search placeholder should indicate how many DAOs I'm in.

## Detail

- Search on _Name_ or a fuzzy search across all table data
- React Table has support for searching across all the table data
- Search component has a dynamic placeholder with amount of DAOs user is in (ie "Search 7 DAOs)
  - Can probably pass this in as the `placeholder` prop on the `Input` used in Search once the data is loaded

## Related Issues

- [#108](https://github.com/HausDAO/daohaus-monorepo/issues/108)
- [#128](https://github.com/HausDAO/daohaus-monorepo/issues/128)

**Comment by alexkeating** [comment]
@skuhlmann Does this even make sense on hub if user has a few daos.

**Comment by jonathanprozzi** [comment]
We can do this with the local data and we can pipe it, but what are implications when we start combining these filters:

- are these all ANDs? 
  - if name contains... AND on this network... AND is a delegate
  - we should build utils to handle this since we'd use this pattern a lot during Core UI (there are several tables) 

When an element goes into the filter dropdown, it can have the query with it, and as you click through the filters it builds up the `where` filter on the query?
  - On any state change we'd re-fetch the query (search debounced or onBlur -- change the state on this, and then this would fire off the new query)
  - state on the input itself and also on the `searchState` 

Challenges and considerations with this:
- Can we turn the entire "Data control" section (sort, filter, search) into a separate component?
- Sort: label and the query that the label passes up (sort based on the label value)
- Each of these can be separate components and combined into a `<Control/>` component -- but we'd want to check with design to be sure that we're going to use the List and Card pattern moving forward in Core UI
  - Will be always be using Card views for mobile moving forward or are we going to do a mobile view for tables? Or will we be needing to support both?
  -
