### ISSUE TITLE
Update Color System + Global Styles (summon)

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#143]
Inputs:
https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=92%3A8758 

Buttons:
https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=67%3A1122

Checkboxes, radios, switches:
https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=44%3A2049

For examples of how these work on light mode:
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=4320%3A63083

Spec includes styles for:
- Input color and states
- Button color and states 
- Standard link style and hover 

Notes:
- The app background for all apps will be Slate/Dark/1 or Slate/Light/1 for light mode
- Each app will have a custom primary (main button actions) and secondary (input backgrounds, default buttons) colors, these current choices are specific to the summon app

**Comment by earth2travis** [comment]
@0xRowdy
