### ISSUE TITLE
Create Avatar Atom Component

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#144]
## Create `<Avatar/>` Component

Create a composable `<Avatar/>` component at the atom level. This should be able to be composed to meet other UI requirements as needed.

In the Pattern Library:

<img width="98" alt="image" src="https://user-images.githubusercontent.com/9438776/167719198-25cc5f9d-5f94-424f-a33c-d759fea27545.png">

In the DAOhaus Connect (will be composed):

<img width="249" alt="image" src="https://user-images.githubusercontent.com/9438776/167719244-98fce65a-ed0c-4dd7-9a23-ac5b9feeb125.png">

## Details

- This is for the atomic component that we'll compose in our UI since we use Avatars for different purposes throughout our apps
- Should take in the Avatar `src` as a prop -- being able to pass in the Ceramic avatar or a potential fallback (such as a blockie) from  `haus-data` 
- Additionally, we may want to think of other props such as `size` to make this composable -- @jordanlesich open to thoughts on this as you build it out
- We may want to explore other packages besides blockie -- this research can be part of this as it's built out

## Related Issues

- #120

## Resources

- https://www.radix-ui.com/docs/primitives/components/avatar
- [Pattern Library Figma Node](https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=147%3A57381)
- [DAOhaus Connect Figma Node](https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=4225%3A40052) Example

## Deliverable

- `<Avatar/>` component added to the component library
- Story added for the component

**Comment by earth2travis** [comment]
Does this need design?

**Comment by jordanlesich** [comment]
Going to look at what the various single use avatars out there in our monorepo and integrate the patterns. 

This ticket will include a static atom avatar that is just UI as well as a higher level avatar that takes in a Profile and handles the control flow (if no url, then blockie, etc) 

Around sizing behaviour, I think I should have the Avatar's container element take the shape of the parent container (some padding for the avatar itsef) with adjustable sizes for props.
