### ISSUE TITLE
Refactor `daohaus-connect` utils into common-utilities

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#149]
# Description

Once the initial functionality is complete identify constants and utility functions that can be moved into the common-utils package.

Dependent tickets:
https://github.com/HausDAO/daohaus-monorepo/issues/120
https://github.com/HausDAO/daohaus-monorepo/issues/121

**Comment by jordanlesich** [comment]
This is ready to go and mostly done. I'd already refactored a lot of utilities that could be used in other libs to commons. 

However, there's probably some elements that I'm missing. If someone wants to take a peek or pair up and see what else can move to commons, I'd be happy to make the changes.

**Comment by skuhlmann** [comment]
More here. Looking good to me
https://github.com/HausDAO/daohaus-monorepo/pull/191
