### ISSUE TITLE
Prepare Contract for Audit Lock

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#15]
This task is to identify all the activities we need to complete to surface a list of contract issues to address before we can lock the contract for audit.

Prepare 

- CLI + Subgraph e2e testing
- Fuzzing

## Issues discovered

https://github.com/Moloch-Mystics/Baal/issues/75

**Comment by earth2travis** [comment]
ConsenSys asked us if we want to use them for Fuzzing

**Comment by earth2travis** [comment]
https://consensys.net/diligence/fuzzing/

**Comment by earth2travis** [comment]
Great to get some fresh eyes on the Solidity code.

**Comment by earth2travis** [comment]
https://ethdoc.io/

**Comment by earth2travis** [comment]
https://github.com/nascentxyz/simple-security-toolkit

**Comment by earth2travis** [comment]
https://github.com/HausDAO/Baal/tree/milestone/audit-715
