### ISSUE TITLE
Refactor InputWrapper Component

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#155]
## Overview

- Refactor our `<InputWrapper/>` to support arrays
- Design requires that a wrapper with label & helper text can support multiple checkboxs, radio buttons, and switches.

https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=37%3A1745

## Deliverable

- [ ] Code/PR that includes the molecule and the types
- [ ] Updated Story for the new functionality

**Comment by jonathanprozzi** [comment]
@0xRowdy -- created this for the work you've been doing to refactor to support arrays

**Comment by 0xRowdy** [comment]
We're able to use existing component to allow multiple checkboxes in one InputWrapper component.
Tracked in this ticket: https://github.com/HausDAO/daohaus-monorepo/issues/27
Branch: https://github.com/HausDAO/daohaus-monorepo/pull/157
