### ISSUE TITLE
Epic: New Proposal View

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#158]
## Description

Core UI dao new proposal view

## Use cases

A connected user should be able to:
- View a list of available proposal forms/types
- Select a proposal type to see the proposal form

## Related features

Core DAO proposal forms
https://github.com/HausDAO/daohaus-monorepo/issues/159

Wallet connect form
https://github.com/HausDAO/daohaus-monorepo/issues/160

Multi-tx form
https://github.com/HausDAO/daohaus-monorepo/issues/161

## Considerations
- User states: Not connected, connected non-member/loot holder, connected share holder

### future considerations
- What if we have 100's of proposal types?

## Available data fields

Proposal types - Priority 1
- Tribute proposal
- Tokens for shares/loot
- Shares/loot request w/out tribute
- Funding request for tokens
- Whitelist/change permissions on shaman proposal
- Change governance settings
- Disperse

Proposal types - Priority 2
- Wallet connect proposal

Proposal types - Priority 3
- Multi TX Builder

**Comment by adriennetilley** [comment]
A number of these have changed for the beta. Not worth trying to update. Closing this ticket.
