### ISSUE TITLE
Epic: Core DAO Proposal Forms

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#159]
# Overview

Proposal form for the core proposal types:

Proposal types - Priority 1
- Tribute proposal
  - Tokens for shares/loot
- Shares/loot request w/out tribute
- Funding request for tokens
- Whitelist/change permissions on shaman proposal
- Change governance settings
- Disperse

## Use cases

A connected user should be able to:
- View the proposal forms, fill in the inputs and submit a proposal
- View the pending tx link and navigate to the block explorer
- See when a proposal/pending tx has resolved

## General Considerations

- Anyone should be able to submit a proposal not just share holders
- How do we handle required fields, error, ect... should mostly be handled in the summoner app/pattern library. 
- Expiration is a time/date and it must be further out than the current time + the voting period + the grace period
- If the DAO has a proposal offering, the form will chage that in native token - we don't need an input for that, but should message the user 

**NEW CONSIDERATION**
- We now need to provide an estimated gas cost for executing the proposal action with each proposal. Our plan is to use the gnosis api behind the scenes to get that estimation.
  - do we want to display that to the user?
  - let them adjust that?
  - let them select 0, which, I think will override the estimation and let the action execute with no gas limit

### Tribute proposal
- Details
  - name, description, contentUrl - mostly optional?
- Tribute token
  - should check approval status when a user puts in the amount and prompt an 'unlock' tx if not approved
- Tribute amount
- Shares requested
- Loot requested
- Proposal expiration date/time - optional

#### Form Considerations

- The user will need to approve the tribute escrow contract to spend their tokens - similar to the tribute token input now
- If the member moves the tokens out of their wallet before the proposal passes and is processed, then the processing will fail. We probably need some messaging for the proposer about that.

Tech details on the tribute escrow contract here:
https://github.com/HausDAO/daohaus-monorepo/wiki/TributeEscrow

### Funding request
- Details
  - name, description, contentUrl - mostly optional?
- Payment token list of tokens the dao is holding
- Payment requested (max button)
- Recipient (address input - v2 also displayed a dao members list to choose from)
- Proposal expiration date/time - optional

### Shares/loot request/award w/out tribute 
Kind of a membership proposal if they don't already have tokens
- Details
  - name, description, contentUrl - mostly optional?
- Recipient (address input - v2 also displayed a dao members list to choose from)
- Shares to mint
- Loot to mint
- Proposal expiration date/time - optional

#### Form Considerations
- Worth doing a guild kick - similar to shares/loot request but it burns the shares/loot or transfer shares into loot?

### Shaman permission proposal
- Details
  - name, description, contentUrl - mostly optional?
- Shaman address
- Permission level
```
    0 = no permission
    1 = admin only
    2 = manager only
    4 = governance only
    3 = admin + manager
    5 = admin + governance
    6 = manager + governance
    7 = admin + manager + governance */
 ```

#### Form Considerations
- Could do one state to set a new shaman and one to change permissions on an existing shaman.
- Fields are the same, the only difference would be to select from existing shamans and their permission level can only go down, so they have less permissions

### DAO Governance change proposal
- Details
  - name, description, contentUrl - mostly optional?
-  voting period length in seconds
-  grace period length in seconds
- new proposal offering in native token amount
- quorum percentage (minimum % of shares that must vote yes for it to pass)
- Sponsor Threshold (minimum number of shares to sponsor a proposal (not %))
- Minimum Retention (auto-fails a proposal if more than (1- minRetentionPercent) * total shares exit before processing - we are defaulting this to 66.66 on new daos)

### Disperse tokens
- Details
  - name, description, contentUrl - mostly optional?
- Token (erc20 or native token)
- Recipients and amounts (list field)

### Relates To

https://github.com/HausDAO/daohaus-monorepo/issues/623
https://github.com/HausDAO/daohaus-monorepo/issues/671
https://github.com/HausDAO/daohaus-monorepo/issues/624
https://github.com/HausDAO/daohaus-monorepo/issues/625
https://github.com/HausDAO/daohaus-monorepo/issues/670
https://github.com/HausDAO/daohaus-monorepo/issues/669
https://github.com/HausDAO/daohaus-monorepo/issues/668
https://github.com/HausDAO/daohaus-monorepo/issues/667
https://github.com/HausDAO/daohaus-monorepo/issues/160
https://github.com/HausDAO/daohaus-monorepo/issues/673
https://github.com/HausDAO/daohaus-monorepo/issues/672

**Comment by adriennetilley** [comment]
@skuhlmann - reviewing this in depth as I spec out each proposal and a few question came up for me: 

> We now need to provide an estimated gas cost for executing the proposal action with each proposal. Our plan is to use the gnosis api behind the scenes to get that estimation.
- Where is this requirement coming from? 

I'm seeing if we can combine 'Tribute proposal' and 'Shares/loot request/award w/out tribute'
- One says 'Shares requested' and other says 'Shares to mint' < I didn't think there was a difference here, but wanted to check 
- Any reason you see to not combine the two?

**Comment by adriennetilley** [comment]
Also - there is a 'considerations' comment mentioning guildkick - seems like one we should add as a default, yeah? Or are we thinking about wrapping that into another proposal type?

**Comment by adriennetilley** [comment]
DAO Governance change proposal - updating the transferability of the tokens isn't on the list, is that still an option?

**Comment by adriennetilley** [comment]
> It's done through a different function so I missed it. Not totally Governance, but for a user it kinda feels like the same area, right?

Yeah, I'd say so. It would feel like overkill to put it into different proposals to me. If we want to be super accurate, the proposal type could be 'Update DAO Settings' and mentioned governance in the subtitle.

**Comment by skuhlmann** [comment]
> Also - there is a 'considerations' comment mentioning guildkick - seems like one we should add as a default, yeah? Or are we thinking about wrapping that into another proposal type?

Yeah I'd say this should be a default proposal. Really just a member select field plus the metadata right?

**Comment by skuhlmann** [comment]
> * Where is this requirement coming from?

This is now an input on the submit proposal function. It's required because we were seeing proposals fail execution when executed without enough gas and then never be executable again. This is the only way they could figure to get around that in the contract.


> 
> I'm seeing if we can combine 'Tribute proposal' and 'Shares/loot request/award w/out tribute'
> 
> * One says 'Shares requested' and other says 'Shares to mint' < I didn't think there was a difference here, but wanted to check
> * Any reason you see to not combine the two?

Yeah makes sense!

**Comment by earth2travis** [comment]
https://github.com/HausDAO/daohaus-monorepo/issues/623
https://github.com/HausDAO/daohaus-monorepo/issues/625
https://github.com/HausDAO/daohaus-monorepo/issues/624

**Comment by adriennetilley** [comment]
Closing, all tickets filed for Proposal forms. Good for future reference.
