### ISSUE TITLE
Deploy Nextra for Baal Docs

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#16]
## What

Update baal documentation to reflect the daohaus fork of the baal/zodiac contract.

https://github.com/HausDAO/Baal

**Comment by wswarren12** [comment]
Review step / peep review: 

Wolflo
Carl 
Scott

**Comment by jonathanprozzi** [comment]
Work in progress: https://baal-docs.vercel.app/

Adding in all of our docs as we have them so far. We can move this from my repo to the Mystics.

**Comment by earth2travis** [comment]
Let's move this repo to the DAOhaus org and close this out. We can create additional issues for filling out content

**Comment by jonathanprozzi** [comment]
Deployment: https://baal-docs.vercel.app/
Repo: https://github.com/hausdao/baal-docs
