### ISSUE TITLE
[DATA] Profile Fetch Bug

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#165]
# Description

- Haus.profile.get() crashes if we pass in an address w/out a ceramic
- Catch error and provide fallbacks

**Comment by alexkeating** [comment]
What is the error?

**Comment by skuhlmann** [comment]
> What is the error?

`TypeError: Cannot use 'in' operator to search for '_tag' in null`

something inside that call to TileDocument.load
