### ISSUE TITLE
Set up Kubernetes and Digital Ocean Infrastructure for the Hub

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#172]
## Overview

This ticket is for setting up the infrastructure needed to support the data processing for the Hub App. We can start with setting up what's needed with Digital Ocean, the initial Docker containers, and Kubernetes cluster. We can also begin thinking about what we'd need for [Helm Charts](https://helm.sh/) and documentation coming out of this process.

## Details

- This may be temporarily blocked until we determine how we want to handle Digital Ocean account setup and payment. If this ends up taking longer than expected we should move forward with the infrastructure setup and figure out this piece afterward

## Deliverables

- [x] Digital Ocean account set up for the DAO*
- [x] Initial Docker containers set up
- [x] Kubernetes cluster scaffolding
- [x] Begin thinking what we'd need for [Helm Charts](https://helm.sh/) and documentation 

*We can work with the Paladins to set this up and work through new processes for this

**Comment by alexkeating** [comment]
@skuhlmann @jonathanprozzi What is the best way to move this forward in terms of payment?

**Comment by jonathanprozzi** [comment]
> @skuhlmann @jonathanprozzi What is the best way to move this forward in terms of payment?

Good question -- Do you think it's pretty safe to say we'll want to use Digital Ocean? If so, I think Sam's idea about buying a set amount of credits is a good approach.

**Comment by alexkeating** [comment]
I don't know if digital ocean has the idea of credits. Because resources are typically a flat rate

**Comment by jonathanprozzi** [comment]
Ah ok. How much do you think our monthly rate would be? I know it's somewhat hard to estimate based on usage numbers fluctuating but maybe we can start there?

**Comment by alexkeating** [comment]
With a production ceramic setup I would say 120 is probably a good start per month

**Comment by alexkeating** [comment]
But we could start as low as $60
