### ISSUE TITLE
Create Input Component

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#18]
# Overview

Create a reusable basic input component.

## Details

Name: `<Input />`

### Spec questions

-  How does this play with form builder and what do we need to consider around that?-
    -  Does it interact with React-Hook-Form
    - Should we spread ...props on it so we can pass anything down?

- Do we want to have different component for the following types?
    - icon on right
    - button on right
    - address full length
    - https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=92%3A8758

#### Variants

https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=92%3A8758

- Filled
- With placeholder
- Empty
- w/ focus (outline)
- w/ Button/drop down appended
- w/ Icon on the right
- Full length address display

#### Props
- placeholder
- key
- id
- name
- onChange
- placeholder
- ref
- disabled
- defaultValue
- appendButton
    - Takes a component (like a button or a select) to append after the input 
    - https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=92%3A8758
- appendIcon
    - Takes an icon component append after the input - like the search icon

## Resources/Design

PL Page: https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=92%3A8758

## Deliverable
- Code/PR
- Storybook deployment

**Comment by jordanlesich** [comment]
Awaiting Button to make button variant. 

Might still be worthwhile to review before then.

**Comment by earth2travis** [comment]
Blocked by: https://github.com/HausDAO/daohaus-monorepo/issues/36

**Comment by jonathanprozzi** [comment]
Closed by #76
