### ISSUE TITLE
Migrate Avatar to component library component

### ISSUE THREAD

**Issue by alexkeating** [HausDAO/daohaus-monorepo#192]
## Overview

Now that https://github.com/HausDAO/daohaus-monorepo/pull/177 is merged in we can integrate it into the Hub App so that we are using the same component across all of our apps.

## Deliverables

- Integrate the `<Avatar/>` component from the component library into the Hub App so that we maintain consistency across our apps via the component library

**Comment by jordanlesich** [comment]
Just a heads up, I made an Avatar component a while back. We probably don't need this anymore

**Comment by alexkeating** [comment]
Did you change the avatar component in Hub to the new one in the component library?
