### ISSUE TITLE
Set up DAO Producer Job

### ISSUE THREAD

**Issue by alexkeating** [HausDAO/daohaus-monorepo#194]
## Overview

Once our Kubernetes Cluster is set up we can create jobs that run. This job will be used in our Hub App for DAO processing. 

## Details

- Create a job that pushes DAOs to queue to be processed
  - Query subgraphs for each DAO in the queue  
  - Drops in the DAO address, safe address fields, network (needed to query for token balances) 

## Deliverables

- DAO Producer Job set up in our infrastructure that supports the Hub App data processing needs

## Related Issues

- #195 
- #172 
- #196

**Comment by earth2travis** [comment]
Requires Helm

**Comment by alexkeating** [comment]
Waiting on this pr to get merged to resolve the esm issues https://github.com/nrwl/nx/pull/10414
