### ISSUE TITLE
Deploy DH Version of Baal Contracts

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#2]
- Fork to DH repo
- Refactor Baal to a size that can be deployed
- Add poster interaction into summoner
- Deploy template/summoner to Rinkeby

**Comment by earth2travis** [comment]
Create `contracts` directory in `daohaus-monorepo`

**Comment by earth2travis** [comment]
Will add new issues for required code changes and branch clean up
