### ISSUE TITLE
Add Pull Request Template

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#20]
Add pull request templates for [Sage](https://github.com/HausDAO/daohaus-monorepo/) repository

**Comment by earth2travis** [comment]
PR template created: https://github.com/HausDAO/daohaus-monorepo/blob/master/.github/pull_request_template.md

**Comment by jonathanprozzi** [comment]
@earth2travis these are added and are being used -- moving to Done.

If we want to modify upon usage we can create a new card to tweak

(mentioned this on the Rage one as well -- working to unclog our Review lane)
