### ISSUE TITLE
Epic: DAO Settings View

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#204]
# Overview

Core ui setting page.

## Use cases

A user can
- view dao general contract info
  - loot and share token name/symbol and contract addresses w/ links to block explorer
  - dao address w/ link to block explorer
  - safe address w/ link to block explorer and gnosis interface 
- view current dao governance settings
  - listing setting in the General Consideration section
- view some current dao metadata
  - listing v2 metadata below
- view current dao shamans + their permission level
  - this might warrant it's own page eventually, but fine as a list for alpha
  - display shaman address and permission level (below)

A dao shareholder can
- open a form to edit metadata
  - change current metadata
  - submit metadata change - this now initiates a transaction
   
- open a form to create governance setting change
  - details for the proposal form are here: https://github.com/HausDAO/daohaus-monorepo/issues/159

- open a form to create a proposal to add a shamn  
  - details for the proposal form are here: https://github.com/HausDAO/daohaus-monorepo/issues/159

## General Considerations

governance settings
- voting period length in seconds
- grace period length in seconds
- new proposal offering in native token amount
- quorum percentage (minimum % of shares that must vote yes for it to pass)
- Sponsor Threshold (minimum number of shares to sponsor a proposal (not %))
- Minimum Retention (auto-fails a proposal if more than (1- minRetentionPercent) * total shares exit before processing - we are defaulting this to 66.66 on new daos)

metadata fields
- name
- description
- avatar image
- links?
- tags?
- long description?
- membership criteria info?
**We should discuss other metadata needs here**

shaman permission levels
    0 = no permission
    1 = admin only
    2 = manager only
    4 = governance only
    3 = admin + manager
    5 = admin + governance
    6 = manager + governance
    7 = admin + manager + governance

## Questions/other inputs needed

- What can we figure out from the shaman address? is it an EOA?
  - check block explorer for abi
  - what else?

## Relates to

https://github.com/HausDAO/daohaus-monorepo/issues/505

**Comment by earth2travis** [comment]
https://github.com/HausDAO/daohaus-monorepo/issues/505

**Comment by 7helles** [comment]
I have a question re: showing "safe address w/ link to block explorer and gnosis interface" - should we have (or plan for) a section showing all associated safe addresses, or is there just going to be one core gnosis safe?

**Comment by adriennetilley** [comment]
Closing, good for reference. 

@7helles - See https://admin.daohaus.fun/#/molochv3/0x5/0x24357654d64da97a55fb2f73c5b66d1927ab1e4c/settings for some adjustments to settings, more addresses. There will be more gnosis safes when you can add more, but I don't think they'll be in settings, just the Main Treasury.
