### ISSUE TITLE
Epic: Member List View

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#205]
Link to figma:
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5365%3A112855 

# Overview

Core DAO ui members list page.

## Use cases

Any user should be able to
- view list of members
  - address/ens/ceramic profile name, share count, loot count, join date
  - indication if they are delegating shares and to what address
  - indicate the # of shares getting delegated to them

- Add a shamans section
  - cross reference member list to help us understand if an EOA
  - link to block explorer

- copy a user address

- sort the list
  - by share count 
  - by loot count
  - by date joined

- navigate the member detail page for each member

- a non member might be able to see some membership info and navigate to a membership proposal

## Spec Notes 

- Shaman column only appears if there is a member with shaman powers

3-dot menu dropdown: 
- Delegate (to user - use same modal as delegate workflow on an individual user profile)
- Guildkick (shares to loot)
- Add Member (mint shares) - later feature
- Promote Member (loot to shares) - later feature

## General Considerations

- We no longer have the concept of jailed members so I removed that filter use case we have in v2

## Relates to:

- https://github.com/HausDAO/daohaus-monorepo/issues/257

**Comment by earth2travis** [comment]
Break ragquit, guid kick and delegate into separate issues

**Comment by adriennetilley** [comment]
Closing. Good for reference in the future.
