### ISSUE TITLE
Epic: Member Detail View

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#206]
# Overview

Core UI Member Detail view

## Use cases

A user can
- view member data
  - address/ens
  - ceramic profile data
    - name, description, emoji, avatar/image
  - join date
  - shares/loot count
  - voting weight
  - current total share of the vault/exit amount
    - break this down by token maybe?
  - indication if they are delegating shares and to what address
  - copy address

A logged in member looking at their own profile can 
- click to edit/edd their ceramic profile
  - this should link to https://self.id/ for now

- change their delegate
  - will open a transaction form to enter the address they want to delegate to, can also be themselves if they want to remove the delegate
  - trigger a transaction

- rage quit shares and/or loot
  - will open a transaction form to enter 
    - share amount/loot amount
    - select tokens they want to exit with
      - this might be advanced mode, in east mode we select all?   
  - trigger a transaction

## General Considerations

- Will need to account for 2 states
  - viewing your own profile
  - view another member's profile 

## Questions/other inputs needed

- Need to do some discovery on what can happen if trash tokens are rage quit.

## Prototype Items to Capture

**Comment by earth2travis** [comment]
Need: 

- Delegate
- Ragequit

**Comment by adriennetilley** [comment]
Closing, good for future reference.
