### ISSUE TITLE
Epic: Create Vault View

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#207]
# Overview

Core UI Vault page.

## Use cases

A user can
- View and copy gnosis safe contract address
  - with links to block explorer and gnosis ui
- view total holding in usd/eth
- view number of tokens and NFTs currently held

A connected user can
- ~~open a form to create a funding/payment request proposal~~ AT 8/24: created on proposal page for now
  -  details https://github.com/HausDAO/daohaus-monorepo/issues/159
  
## General Considerations

- Initially we will develop for a single, rage-quitable vault, but in the future we might need to work on extra vaults that are not rage-quitable, similar to minion vaults today.

- I have left chart/graphs out of this alpha list. Feels like a Reporting bolt-on to me, but could be considered for future core iterations.

- (Avi, 8/22 - moving this down here) Also not alpha list: 
 - view a list of current tokens held
  - network token, erc20
    - name, symbol, balance, current price in usd/eth, balance in usd/eth
    - contract address w/ block explorer link
  - erc721/erc1155
      - contract address w/ block explorer link
      - tokenId
      - token uri/metadata (whatever we can find here)
      - image if applicable (need a fallback)

- Allow members to name and hide

## Prototype Items to Capture

**Comment by skuhlmann** [comment]
https://app.daohaus.club/dao/0x64/0xef3d8c4fbb1860fceab16595db7e650cd5ad51c1/vaults/minion/0xab0558f4750979215350379296631d2c890dbe8d

vault with extra signers

**Comment by skuhlmann** [comment]
@adriennetilley 

Did a little legwork on implementation paths for the secondary vaults. Once we have some better ideas on workflow for installing them I'll let you know. But that shouldn't change the stuff we review and what you're thinking for displaying them in alpha ui.

- naming, renaming and hiding is good to go with a transaction
- i think differentiating between the main treasury and these extra vaults will be important
  - rage quit-able vs. non
  - you can't name/hide the main treasury

**Comment by adriennetilley** [comment]
Closing up, notes on what was/wasn't included in beta release. Good for future reference.
