### ISSUE TITLE
Create Input Label Component

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#22]
# Overview

Create a reusable basic input label component.

## Details

Name: `<Input />`

### Spec questions

- Dependent on some Typography
  - text: `<Text />`

#### Variants

https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=92%3A8758

- w/ and w/out required indicator
- w/ and without ToolTip

#### Props
- labelText
- toolTip
    - Maybe this Takes a component to append after the label
    - https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=92%3A8758
- isRequired

## Resources/Design

PL Page: https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=92%3A8758

## Deliverable
- Code/PR
- Storybook deployment

**Comment by jordanlesich** [comment]
We can probably merge this into the wrapper or tooltip. Most of the work is getting the tooltip working.

**Comment by jordanlesich** [comment]
Input Label won't be able to compose a Body text component because it needs to be a <label /> in order to be accessible.
