### ISSUE TITLE
Create useViewport Hook

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#229]
## Overview

Create a `useViewport` hook that can be used to detect the viewport size for use with mobile layouts.

Blocked by #240

## Deliverables

- [ ] `useViewport` hook added to either `utils` or `haus-components` package

## Detail

- I added the `haus-components` label for this -- not sure if where we'd want to include this hook. Maybe in our `utils` instead of the `haus-components` ? Figure we'd likely leverage this hook in the component library either way.
- We could perhaps look at the `useMediaQuery` hook in Chakra: https://chakra-ui.com/docs/styled-system/utility-hooks/use-media-query for some inspiration

## Related Issues

- This issue is currently blocking #234

**Comment by earth2travis** [comment]
Blocked by https://github.com/HausDAO/daohaus-monorepo/issues/240
