### ISSUE TITLE
Create Toast Hook

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#230]
## Overview

Create a hook to support use of Toasts throughout our app. We may want to leverage a similar `OverlayContext` pattern used throughout v2.

## Deliverables

- [ ] A `useToast` hook added to support our Toast components
- [ ] (optional) `OverlayContext` pattern (or at least testing to see if our implementation would support this approach) -- defer to you on this one @jordanlesich!

## Details

- Should we look to refactor/reuse patterns such as the in the `OverlayContext` in v2? (https://github.com/HausDAO/daohaus-app/blob/develop/src/contexts/OverlayContext.jsx)
  - This version leverages the `useToast` hook from [Chakra](https://github.com/chakra-ui/chakra-ui/blob/main/packages/toast/src/use-toast.tsx), so we may be able to look to this for inspiration for this hook

## Related Issues

- #237 

## Resources

- [Chakra UI useToast Code](https://github.com/chakra-ui/chakra-ui/blob/main/packages/toast/src/use-toast.tsx)

**Comment by jonathanprozzi** [comment]
@jordanlesich -- i added some additional notes here, but i know you also have more context for this than i do!

**Comment by jordanlesich** [comment]
@jonathanprozzi Notes are good. Going to jam this in HausThemeContext I think.
