### ISSUE TITLE
Create Modal Component

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#231]
## Overview

Create a reusable `<Modal/>` component that we can use throughout our apps. We may need additional design support on this --[ Figma Link](https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=895%3A91491)

Main Modal:

![Image](https://user-images.githubusercontent.com/9438776/172228775-f06d374a-805b-44b2-b3d8-9e61ca9a4226.png)

The Figma has variants that stem from the main Modal component (these are in the _Modal Variants_ section in the Figma link).

## Deliverables

- [x] `<Modal/>` component added to the `haus-components` package
- [x] Story added for the component

## Details

The Figma has variants that stem from the main Modal component (these are in the _Modal Variants_ section in the Figma link):
- One button (bottom right)
- One button (bottom left)
- Two buttons (bottom right)
- Two buttons (bottom left)
- Two buttons (bottom left), one button (bottom right)
- One button (bottom left), one button (bottom right)
- Two buttons (bottom left), two buttons (bottom right)

**Comment by 7helles** [comment]
Figma component can be found here: https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=895%3A91491

**Comment by jonathanprozzi** [comment]
Thanks!

**Comment by 0xRowdy** [comment]
@7helles Any info around the background overlay for the modal?
