### ISSUE TITLE
Update component library colors to match new pattern library decisions

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#232]
## Overview

Update the component library to use our colors in our Figma pattern library. The default colors and color guidelines are linked in the _Resources_ section below.

## Deliverables

- [ ] Component library colors updated in the theme object

## Resources

- [Figma Link: Default Colors](https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=797%3A91791)
- [Figma Link: Color Guideline/Color System Info](https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=759%3A90496)

**Comment by earth2travis** [comment]
How does this relate to #133

**Comment by earth2travis** [comment]
@jonathanprozzi
