### ISSUE TITLE
Revisit Link Component

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#233]
## Overview

Our current implementation of the Link component uses a temporary link. This adds in the ability to support both `react-router` Links and external links using anchor elements. 

## Deliverables

- [ ] Design considerations for how we want to handle internal vs. external links
- [ ] Link component refactored and updated to support both internal (react-router) and external (anchor element) links

**Comment by earth2travis** [comment]
External links have an icon to open new window

**Comment by earth2travis** [comment]
@0xRowdy are you still working on this?
