### ISSUE TITLE
Create DAOhaus Connect: Mobile Views

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#234]
## Overview

Build the mobile view for DAOhaus Connect. 

![Image](https://user-images.githubusercontent.com/9438776/171770710-65f1b45b-f070-4bac-b5b2-2ef2e98adccd.png)

Note: This is currently blocked by #229 

## Deliverables

- [ ] Mobile views added for DAOhaus Connect for each of the various states, the wrong network indicator, and the dropdown menu of available networks.

## Detail

- Once the `useViewport` hook is in place we can use that for detecting mobile
- There are mobile views for each of the following states already represented in DAOhaus Connect:
  - Default connector 
  - Loading connector
  - Connected > Closed
  - Connected > Open
  - Wrong Network
  - Available Networks dropdown 

## Related Issues

- Blocked by #229 

## Resources

- [Figma Link](https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=4225%3A40043)

**Comment by earth2travis** [comment]
Blocked by useViewport Hook [#229](https://github.com/HausDAO/daohaus-monorepo/issues/229) which is blocked by Define Breakpoints [#240](https://github.com/HausDAO/daohaus-monorepo/issues/240)
