### ISSUE TITLE
Create Toast Component

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#237]
## Overview

Create a `<Toast/>` component that supports several different variants (success and error, for example) can be used throughout our apps.

![Image](https://user-images.githubusercontent.com/9438776/171768868-b2adefed-0f3c-4aeb-b561-4f7dfec5818e.png)

## Deliverables

- [ ] A `<Toast/>` component added to the Component Library
- [ ] Stories added to the Storybook for the Toast variants

## Details

- We have success and error variants, and examples of each that support the following:
  - Icon (such as success and error icons in the top left)
  - Left link
  - Right link
  - Left and right links

## Related Issues

- #230 

## Resources

- [Pattern Library Figma Link](https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=797%3A92905)

**Comment by earth2travis** [comment]
Any updates on this @0xRowdy?

**Comment by earth2travis** [comment]
@7helles we may need to add a warning state for toasts in the Pattern Library
