### ISSUE TITLE
Define Breakpoints

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#240]
## Overview

Define the breakpoints that we want to use for responsive design. We'll implement this into our component library theme and also tap into it with #229 to create responsive layouts.

## Details

- What do we want to set for each breakpoint? We can specifically think of the device or more generally like Chakra does:

```
const breakpoints = {
  sm: '30em',
  md: '48em',
  lg: '62em',
  xl: '80em',
  '2xl': '96em',
}
```

- Can also map to the Chrome Dev Tools breakpoints, but this may be a bit too much. This is referenced in [this article](https://jsramblings.com/how-to-use-media-queries-with-styled-components/).

```
const size = {
  mobileS: '320px',
  mobileM: '375px',
  mobileL: '425px',
  tablet: '768px',
  laptop: '1024px',
  laptopL: '1440px',
  desktop: '2560px'
}
```

**Comment by jonathanprozzi** [comment]
@oovg tagging you in this one since it came up during Planning today

**Comment by earth2travis** [comment]
@jonathanprozzi let's add the details about what breakpoints are needed and get it ready for design

**Comment by oovg** [comment]
xs - phone - maxWidth: 480px
sm - tablet - maxWidth: 768px
md - desktop - maxWidth: 1024px
lg - large desktop - maxWidth: 1200px
xl - xl screens - minWidth: 1201px
