### ISSUE TITLE
Create DAO Card Component

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#244]
## Overview

Create the DAOs Component card for use in the Grid view. These take in the same data used in the _DAO Table_ view and display the DAO's info as a card.

![Image](https://user-images.githubusercontent.com/9438776/175979205-409337c4-7ae3-43f6-a3b7-91a568b7c1c7.png)

## User Stories

- As a connected user viewing the _Grid view_, each DAO Card should display information about a DAO I'm in.
- As a connected user who is a delegate, the DAO Card for the DAO I'm a delegate in should display a tag showing this.

## Details

- DAO logo/icon (proposal count is a stretch goal -- can add later in a separate ticket)
- If user is the Delegate for the DAO, display a _Delegate_ tag in the top right
- Each card should display the following as text:
  -  DAO name
  - Member count
  - Treasury/vault value
  - Proposal count
  - Voting power

- Each card should display the following as tags:
  - Chain
  - DAO type (ie "Moloch V2")

- Link to the DAO on DAOhaus v2

## Related Issues

- #243 is the grid view that uses these cards

**Comment by earth2travis** [comment]
How does this relate to https://github.com/HausDAO/daohaus-monorepo/issues/258

**Comment by skuhlmann** [comment]
> How does this relate to #258

Oh we missed that one Ven had added. #258 can be the ticket of truth.

**Comment by jonathanprozzi** [comment]
Closed by PR https://github.com/HausDAO/daohaus-monorepo/pull/314
