### ISSUE TITLE
Create Profile Dropdown

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#246]
## Overview

Create the Profile dropdown that shows up in the Profile Header component when a user's wallet is connected. This dropdown has two items: _Edit SELF_ID_ and _View Public_

![Image](https://user-images.githubusercontent.com/9438776/172431032-964a824e-a9c4-4c30-97ba-6782d89e4e03.png)

![Image](https://user-images.githubusercontent.com/9438776/172431155-96df0cfc-2043-41ce-a6b4-eac584c3a8c0.png)

## Details

- The _Edit SELF_ID_ is an external link to self.id 
- The _View Public_ is an internal link to the _/:address_ route for the Profile being viewed
- Can likely leverage the Dropdown component used in DAOhaus Connect

**Comment by skuhlmann** [comment]
This is almost done - we just need to add the url/external link to SELF_ID

**Comment by alexkeating** [comment]
The external link should be https://self.id on prod and https://clay.self.id in test environments
