### ISSUE TITLE
Create Table Component

### ISSUE THREAD

**Issue by oovg** [HausDAO/daohaus-monorepo#257]
Automate some of the data pieces. Flexible cells that take in table elements. Do when we create the first table. See where we are doing this with Hub and what can be automated

Relates to:

- https://github.com/HausDAO/daohaus-monorepo/issues/205

**Comment by skuhlmann** [comment]
https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library?node-id=1475%3A265385

**Comment by earth2travis** [comment]
Let's not build a builder
Review updates to React Table v8.

**Comment by skuhlmann** [comment]
I did this. Closing.
