### ISSUE TITLE
Create Card Component

### ISSUE THREAD

**Issue by oovg** [HausDAO/daohaus-monorepo#258]

**Comment by earth2travis** [comment]
How does this relate to https://github.com/HausDAO/daohaus-monorepo/issues/244

**Comment by earth2travis** [comment]
@0xRowdy

**Comment by 0xRowdy** [comment]
I created and completed a Basic Card component that consists of the following.
background color - default, hover, focus, disabled?,
border - default, hover, focus, disabled?,
border radius,
and padding.

We can extend this card and customize it for more specific cards like DAO Details Card.

**Comment by earth2travis** [comment]
Already done
