### ISSUE TITLE
Create Layout Component

### ISSUE THREAD

**Issue by oovg** [HausDAO/daohaus-monorepo#266]
# Details

Component to support the one-column layouts seen in core ui:
- Vault/members/settings pages
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6037%3A140410
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5359%3A118119

**Overview and member profile page**
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5522%3A113968
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6037%3A140410

- [x] optional page title
- [x] optional 'actions' button area

#### Legacy notes

Create components to replace `<TemporaryLayout />`

Should be high level page layout components for `hero` and `body`

**Comment by earth2travis** [comment]
@oovg could you sync up with @jordanlesich to determine if what was implemented is okay?
