### ISSUE TITLE
Add READMEs to Repos

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#276]
Add/update README files to/in:

- [ ] monorepo (top level)
- [ ] subgraphs
- [ ] sdk
- [ ] commons
- [ ] DAOhaus Connect
- [ ] summon
- [ ] hub
- [ ] component library
- [ ] helm
- [ ] kubernetes
- [ ] ceramic node
- [ ] subgraph node
- [ ] jobs
- [ ] apps (top level)
- [ ] libs (tol level)

Relates to:

https://github.com/HausDAO/daohaus-monorepo/issues/116
https://github.com/HausDAO/daohaus-monorepo/issues/117
https://github.com/HausDAO/daohaus-monorepo/issues/275

**Comment by earth2travis** [comment]
https://github.com/HausDAO/daohaus-monorepo/wiki/Local-Development-Environment

**Comment by earth2travis** [comment]
Are there other directories that need READMEs that are not listed here?

**Comment by jonathanprozzi** [comment]
https://github.com/HausDAO/daohaus-monorepo/tree/feature/add-package-readmes

work in progress

https://hackmd.io/FZ6_JQZESr-dBA9g7uQNBw
