### ISSUE TITLE
Create Switch Component

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#29]
# Create `<Switch/>` Component

Create a reusable basic `Switch` component for use in the DAOhaus forms.

## Details

Name: `<Switch />`

### Spec questions

- Like the other inputs, we'll want to think about how this interacts with `react-hook-form` and FormBuilder
- Look to [Radix's Switch Component](https://www.radix-ui.com/docs/primitives/components/switch) -- This has accessibility features like keyboard navigation and support for controlled/uncontrolled out of the box. Support for controlled will likely be relevant depending on how we integrate React Hook Form.

#### Variants

https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=44%3A477

- Basic input (look to the _Switch Master_ in the Figma file)

Similar to the Checkbox and Radio, each of these states will also need to include the indicator for _required_ and for when it's _not required_ (this is represented in the Figma file)
- Active State (toggled 'on')
- Inactive State (toggled 'off')
- w/ Label (above)
- w/ Label (beside)
- w/ Label (above and beside)
- w/o Label (will need to ensure that this still is accessible -- may need a hidden label for screenreaders)
- w/ Label (above and beside)
- w/ Tooltip (info icon)

#### Props

- label
- placeholder
- key
- id
- name
- onChange
- placeholder
- ref
- disabled
- defaultValue
- appendComponent
    - Takes a component (like a button or a select) to append after the input 

## Resources/Design

[Figma PL Node](https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=44%3A477)

## Deliverable

- Code/PR
- Storybook deployment

**Comment by jordanlesich** [comment]
Revised Spec for Switch: 

This spec written above was written before many of the patterns around form elements were established. Here's an update that provides a more up-to-date view of what's needed. 

 ### Spec Questions 
 - Switch should extend ref using the React.forwardRef pattern 
 - This switch uses Radix's Switch component (same as mentioned above) 
 - Follows pattern of other form elements
 - We need to build an atom switch (base element + styles) + a wrapped switch for use with React hook form
 
 We can see an example of how this is done 
 Component 
 https://github.com/HausDAO/daohaus-monorepo/blob/develop/libs/ui/src/components/atoms/input/input.tsx
 and the input Wrapper here
 https://github.com/HausDAO/daohaus-monorepo/blob/develop/libs/ui/src/components/molecules/wrappedInput/wrappedInput.tsx
 
 
 We also need separate
 
 Variants
https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library-(In-Progress)?node-id=44%3A477

The FieldWrapper component is
