### ISSUE TITLE
Add Component Sync Meetings

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#30]
Based on feedback from the [April 1, 2022 Retro](https://github.com/HausDAO/daohaus-monorepo/wiki/Retro:-April-1,-2022) we need to improve the integration between design and development teams.

We decided a good step towards this goal would be recurring meetings to discuss the component library on Tuesday's at 15:00 CDT. This should be enough time to align as the component library is getting built.

We may choose to have these meetings on an ad hoc basis after a system is put in place.

**Comment by earth2travis** [comment]
Meeting invite: https://calendar.google.com/calendar/u/0/r/eventedit?text=v3+Component+Sync&dates=20220405T200000Z/20220405T210000Z&details=Discuss+v3+component+library+and+align+design+and+development+teams&location&sf=true

**Comment by jonathanprozzi** [comment]
This can probably be moved to Done since it's set up unless you want to wait until we lock in a good time for repeat meetings

**Comment by earth2travis** [comment]
https://github.com/HausDAO/daohaus-monorepo/wiki/Meetings#component-sync

**Comment by earth2travis** [comment]
Maybe we should flesh out the wiki a little bit more about what this meeting is and how it should go down. Then we can move it into Review to keep our eye on it next week and add any additional thoughts or concerns about how it is working out

**Comment by jonathanprozzi** [comment]
That sounds like a good plan!

**Comment by earth2travis** [comment]
Meetings were done ad-hoc this week and moved things forward. We may also consider having some syncs and deep dives on features coming down the pipeline.

**Comment by earth2travis** [comment]
These meetings seem to be going well. Still a lot of async discussions happening too. Just need to make sure the decisions are captured and we take notes on the meetings.
