### ISSUE TITLE
Create the DAO Context

### ISSUE THREAD

**Issue by jordanlesich** [HausDAO/daohaus-monorepo#303]
## What
- [x] Build effects that handle DAO-scoped queries on context load or DAO change
- [x] Effects receive DAO address from url
- [x] Ensure that effects refire when daoaddress is changed
- [x] Ensure that we're handling cases where a DAO data is not found
- [x] Store members, proposals, daoMetadata in context

- refresh function (refetch all entites, but holds filter and pagination
1. get 3 domains - dao, members, proposals
- [x] set up and wrap dao routes
- [x] refresh function
- [ ] polling

2. handle pagination and filtering
```js
const { members, filterMembers, sortMembers, getMoreMembers } = useMembers();
```
- [x] pagination
- [x] filtering
- [x] sorting

reset filters/sort/page?
- not now

## Bonus Round
- Pull in TXBuilder context and get a TX to trigger a reload. 

## Exploration
- What happens if we initiate a DAO proposal query at the page level instead of the context level? 
    - If we do initiate at page level, what happens when we paginate? How will we handle stale data? 
    - How does paginated data work with a total refresh of DAO state post TX?

**Comment by skuhlmann** [comment]
@jordanlesich 

I can't remember, did this rage ever happen?

I feel like most of this is still relevant to building out dao context this week. We can discuss and spec from here. Pagination (and potentially updating the entity query filter for things like a proposal list) is still the biggest question in my mind. Will be good to sort out.

**Comment by jonathanprozzi** [comment]
(dropping my notes in)

# DAO Context Sync (7/19/22)

- DAO overview
  - From context, being able to pull DAO overview/DAO metadat (doesn't need a filter)
- Members
  - DAO members query with the DAO address in the param and paginated to ~20 people
  - Can then pull members anywhere in the app (currently paginated to 100)
    - How would I pull *next* from the Members page -- would we use a `getNextPage` of members?
    - This would change the state in the context
  - `getNextMembers` -- pile these on to the previous list (can do an Infine Scroll or a Show More for the UX)
- Proposals
  - Have a hook for filter that adds the filter in
    - Should be able to handle any of the modifiers we'd pass in
    - Context methods that we turn into hooks

## Example Hooks

```js
const {members, filterMembers, getMoreMembers} = useMembers()
```

- These are hooks that would be exposed -- this fits with the SDK patterns pretty well
- Tradeoff is that this'll be a large Context
- How would we surface specific individual proposals?
- We'd hold all of the SDK call parameters in state and when we refresh we'd call again with the same parameters

## Questions

- What stays after a refresh?
  - Filter, sort, pagination limitations
    - Would want the same number of members that are showing
- Would there be a use case to completely reset the filters/sort/pagination limit?
  - Potentially down the road, but for now we won't include this
- Would handle route changing -- this was a pain point in the v2

## Tradeoffs

- If we do this at page level, we'd lose the overarching drag and drop context (would just be overview) but then we'd lose the query results from moving between pages
- Simple DAO context, but when we'd get to proposal list we'd need to include this data anyway
