### ISSUE TITLE
Update Hub colors to match the new design

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#309]
## Overview

The new Hub designs use the same colors as Summoner. The custom `crimson` and `crimsonDark` colors need to be removed so that this matches.

![Image](https://user-images.githubusercontent.com/9438776/175988145-4146c191-5d7d-4de2-a0dd-d35b9cced484.png)

## Details

-

**Comment by earth2travis** [comment]
Get this merged in and branch off it

**Comment by earth2travis** [comment]
Should be pulling to theme. Need to remove the overrides

**Comment by jonathanprozzi** [comment]
https://github.com/HausDAO/daohaus-monorepo/pull/311

**Comment by jonathanprozzi** [comment]
Closed by https://github.com/HausDAO/daohaus-monorepo/pull/311
