### ISSUE TITLE
Tag Component

### ISSUE THREAD

**Issue by jordanlesich** [HausDAO/daohaus-monorepo#316]
A tag component should:

- render a bg color and corresponding text color from Radix colors
- Take in a simple radix color string as props (enum)
- render children with these styles

Would likely need to store Radix color values in object enums to avoid complex patterns to navigate their data structure. 

- Perhaps start with 6 or so colors then add as we need.

**Comment by 0xRowdy** [comment]
Is #255 a duplicate?

I've built this out. with 4 colors that I chose. Blue, green, pink, and violet. I'd like to get some feedback from design on the colors and can add another 2.

**Comment by jonathanprozzi** [comment]
Closed by https://github.com/HausDAO/daohaus-monorepo/pull/349
