### ISSUE TITLE
Unit Manipulation utils.

### ISSUE THREAD

**Issue by jordanlesich** [HausDAO/daohaus-monorepo#317]
Unit manipulation utils. These are in V2. 

They just add suffixes like 'k' or 'M' to number strings that are over a certain size (ex 30000 vs 30k). I used a lib. Forget which one. We need these for a lot of things in the hub app.

Test with DAO cards.

**Comment by skuhlmann** [comment]
Can this also handle display of USD?

27.3595 to 27.36 usd

![Image](https://user-images.githubusercontent.com/6923345/177373171-1c77dec5-2e20-4583-939d-e625ec710b0d.png)

**Comment by jordanlesich** [comment]
Yep!
