### ISSUE TITLE
Create Issue Template for Components

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#34]
Create an Issue Template for all the component cards we are creating. This can be done in Markdown to standardize the appearance of all the component related cards. Should include any checklists that need to be completed in the various columns of the Kanban board.

[Configuring issue templates for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by jonathanprozzi** [comment]
This relates to the PR from last week: https://github.com/HausDAO/daohaus-monorepo/pull/19

We can see if we want to update this template or start fresh @earth2travis

**Comment by jonathanprozzi** [comment]
Also started this doc where we can jam about this and other templates: https://hackmd.io/6yUQpMRXTLWk_m3UbTLZjg

**Comment by earth2travis** [comment]
Add checkboxes for design

- Empty states
- Variants
- Error states
- Accessibility

**Comment by jonathanprozzi** [comment]
This is added here: https://github.com/HausDAO/daohaus-monorepo/blob/master/.github/ISSUE_TEMPLATE/component-library-spec.md

This is updated based on our previous Review. I'm going to move this into _Done_ and we can revisit if needed.
