### ISSUE TITLE
Update Logic on Delegate tagging

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#362]
# Details

double check logic and adjust if needed to use sdk:
- isDelegate
- delegatngTo

- [ ] card view
- [x] list view

dependent on
https://github.com/HausDAO/daohaus-monorepo/pull/357

**Comment by jonathanprozzi** [comment]
@skuhlmann -- can use a Cell renderer to conditionally show the Tag:

this is the accessor for the name, so we could add it to the return here

```
  {
        accessor: 'name', // accessor is the "key" in the data
        Cell: ({ value }: { value: string | undefined }) => {
          return (
            <FirstCell>
              <Avatar size="sm" fallback={<BiGhost />} />
              {value}
            </FirstCell>
          );
        },
        Header: () => {
          return <FirstHeader>3 Daos</FirstHeader>;
        },
      },
```

**Comment by jonathanprozzi** [comment]
This relates to #360 as well
