### ISSUE TITLE
Add placeholder to the Docs link on Summon (or remove it)

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#364]
## Overview 

The _Docs_ link at the top of Summon doesn't go anywhere. I know we're still figuring out where this should go, so maybe we add a placeholder or remove it until we lock it in to avoid unexpected behavior.

**Comment by earth2travis** [comment]
This was completed in https://github.com/HausDAO/daohaus-monorepo/issues/494
