### ISSUE TITLE
Adjust default quorum % on Summon

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#366]
## Overview

Look into what our default quorum % is on the Summon form. From QA:

```
 default for quorum % should be 0%. Though it might be good to be able to adjust the default based on whether voting staking transferability is turned on. If that's easy/possible, I'd suggest we set the default as such...
- 0% if voting stake is not transferable
- 20% if voting stake is transferable
```

![Image](https://user-images.githubusercontent.com/9438776/177383890-c98935c6-fa54-49ee-a316-579c473af9d0.png)

Additional note: 
```
some nuance to this one: need to be careful not to override a user's actual quorum % input if they change the transferability toggle. Should only change the default value, ie if the user hasn't input anything
```

## Details

- For now we can set this default % to 0%
- Should be a quick update to the default value on the `quorum` input

**Comment by skuhlmann** [comment]
@jonathanprozzi 

We could just adjust this to 0% across the board as a quick fix.

**Comment by jonathanprozzi** [comment]
That sounds good -- we can roll this out as a quick fix and then see if we want to dive deeper. Going to move to Spec

**Comment by skuhlmann** [comment]
Pushing the 05 default in a pr now.
