### ISSUE TITLE
Update Shaman Link on Summon Form

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#367]
## Overview

In the Summon form we're using a temporary link to the Baal docs Shaman section. This is good for now, but we'll need to update this in both cases:
- 1) we decide we want to use a different link to another docs page
- 2) we add a subdomain to the current Baal docs (and we'll need to change the URL in the Shaman form since it's using the current 'staging' URL for the docs)

We could probably expand this further and add these links to our constants, but for now we wanted to update this ticket to be clearer about what still needs to be done.

**Comment by earth2travis** [comment]
Should we link to this: https://baal-docs.vercel.app/tools/shaman

**Comment by earth2travis** [comment]
Should probably wait to update the link after the docs are deployed to the subdomain

**Comment by jonathanprozzi** [comment]
@earth2travis Changing the description to reflect the current state of this after your recent fixes

**Comment by skuhlmann** [comment]
this is updated, but i'm not seeing it on the live site yet.
