### ISSUE TITLE
Add helper copy about the accepted space delimiters in the Starting Shamans and Starting Members sections

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#368]
## Overview

We can add some helper text/tooltip to clarify which delimters are accepted in our inputs that take an address with another value For example, in the Members list in the **Starting Members** section:

![Image](https://user-images.githubusercontent.com/9438776/177385185-a6107133-0817-4d65-a72a-9846834d340e.png)

We also see this in the **Starting Shamans** section.

**Comment by skuhlmann** [comment]
https://github.com/HausDAO/daohaus-monorepo/pull/370/files
