### ISSUE TITLE
Create an Address Component

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#386]
Figma specs:
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6242%3A136826

All contract addresses will have the same pattern, copy address with toast popping up after (see 'Share Profile' button interaction in the hub profile). And a 'link' icon that takes them to the relevant chain etherscan or blockscout link in a new tab. 

Two versions:
- Shortened/truncated
- Full address 

![Image](https://user-images.githubusercontent.com/42706432/181256103-d01a0dec-e748-417d-9e42-3a21c4ca27fb.png)

**Comment by earth2travis** [comment]
Needs design spec

**Comment by adriennetilley** [comment]
spec complete

**Comment by skuhlmann** [comment]
Going to add some helpers here for:

- external link to block explorer by type - contract/address/txHash
- copy to clipboard helper or something
