### ISSUE TITLE
Create an Indicator Component

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#388]
## Overview

Create a reusable component for the "Indicators" used throughout the apps. 

## Details

- Large data display and a small data display options (see in figma) 
- Would potentially include a Label, data field, and allow for a Tooltip
- Would support a few variants of this but the core component would contain the above elements (label, data field value, optional tooltip)

## Figma

https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6242%3A136826

**Comment by skuhlmann** [comment]
![Image](https://user-images.githubusercontent.com/6923345/180057777-ae46acfa-19bb-4bef-a6f6-c919062506d0.png)

**Comment by earth2travis** [comment]
@adriennetilley can you please add a link to the related areas in the Figma file?

**Comment by adriennetilley** [comment]
Spec added, this is ready to go

**Comment by skuhlmann** [comment]
dropping a screenshot of the w/ tooltip state



![Image](https://user-images.githubusercontent.com/6923345/180275619-6129558a-55b3-4d28-9a7d-47d855511477.png)
