### ISSUE TITLE
Create a Badge Component

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#391]
Figma specs: https://www.figma.com/file/R1a1bwODnzCHHHw0EJALAU/DAOhaus-v3-Pattern-Library?node-id=1332%3A258312

**Comment by adriennetilley** [comment]
These specs seem ready to go

**Comment by skuhlmann** [comment]
https://github.com/HausDAO/daohaus-monorepo/pull/525
