### ISSUE TITLE
Fix the Hub Disconnected Homepage 404 on the Illustration

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#395]
### Feature

Exploring the Hub UI as a disconnected user

### Expected outcome

The Hub illustration shows to the right of the Hub hero section.

### Actual outcome

The Hub illustration results in a 404 when loading. 

### Browser

Brave, Chrome

### Screenshots and context

![Image](https://user-images.githubusercontent.com/9438776/185917703-3fd86040-08df-4d73-85b4-2d1823c73ff0.png)

![Image](https://user-images.githubusercontent.com/9438776/185917754-9895819d-6d05-4a0e-8f91-7f2cd619dac2.png)

## Details

- The illustration loads properly when working locally, so the issue has to do with production deployments. As outlined by the issue that @earth2travis linked (and I also checked other Vite apps I've deployed) and it looks like we want to have this in the `/public` assets folder instead of where we have it in `src` 
  - This is a starting point but this may be tricky to test since it'll require a deployment to fully check the fix

**Comment by earth2travis** [comment]
@jonathanprozzi this issue card has not been filled out yet

**Comment by earth2travis** [comment]
https://github.com/vitejs/vite/issues/3980

**Comment by jonathanprozzi** [comment]
PR: https://github.com/HausDAO/daohaus-monorepo/pull/711
