### ISSUE TITLE
Action Data Display

### ISSUE THREAD

**Issue by jordanlesich** [HausDAO/daohaus-monorepo#404]
# Details

Proposal details page action data.
- Takes proposal action data from the proposal entity
- Decodes
- fetch abi for each contract address
  - uses new txbuilder abi cache and helper utils
- displays contract address, action/function name, arg values
- lists each action
- each contract address has a copy icon and a block explorer link

IF WE CAN'T DECODE THE DATA FOR SOME REASON WE SHOULD HAVE A FALLBACK THAT JUST DISPLAYS THE RAW HEX DATA.

Arg types:
- try to detect array types and list in a bulleted list with index position

Challenge:
- What if an action is a nested action call
- Might need to recursively call it self if the action is a list of other action data 

https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5549%3A115198

![Image](https://user-images.githubusercontent.com/6923345/184694960-6bcdc7d3-499a-4c3c-ad75-2a3b510e9c72.png)

**Comment by earth2travis** [comment]
Need to account for the data types that come back from the contracts

**Comment by earth2travis** [comment]
@adriennetilley we need design for the error state when it cannot be decoded
