### ISSUE TITLE
Create App Switcher Component

### ISSUE THREAD

**Issue by jordanlesich** [HausDAO/daohaus-monorepo#405]
# Details

Simplified version of the nav drop down that will be used to nav between summoner and hub.

- Takes in an array of links and clickable JSX to be rendered
- Opens other apps when clicked in new window

We will not do the Search feature in this ticket.

https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6183%3A133289

![Image](https://user-images.githubusercontent.com/42706432/181630042-5f4ee421-1ee5-4d97-ac84-e1c10b80de58.png)

Relates to:

https://github.com/HausDAO/daohaus-monorepo/issues/65

**Comment by adriennetilley** [comment]
![Image](https://user-images.githubusercontent.com/42706432/181629895-3f2b54e7-8c9c-4017-a8ed-0d154a42bbab.svg)
![Image](https://user-images.githubusercontent.com/42706432/181629897-7c6e2217-de27-48d2-aed5-c24174c609ed.svg)
![Image](https://user-images.githubusercontent.com/42706432/181629896-13b50ea9-4569-44ec-b707-fe9613ba7be2.svg)

**Comment by earth2travis** [comment]
Hub icon should already be available

**Comment by 0xRowdy** [comment]
Very similar to #429 which is already in flight. Just more specific variants of drop-down.

**Comment by earth2travis** [comment]
@santteegt are you able to take this component this week?

**Comment by earth2travis** [comment]
May be related to: https://github.com/HausDAO/daohaus-monorepo/issues/429

**Comment by 0xRowdy** [comment]
Need a little clarification on the SVGs and where they are coming from? 
Will the colors already be applyed to the SVG when we get it, is it stored in the UI Repo or an external place?
