### ISSUE TITLE
Hub Refactor: Prop drilling and Hook for the fetch useEffect

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#410]
mentioned here:
https://github.com/HausDAO/daohaus-monorepo/pull/401#pullrequestreview-1036156212

Keating started this for the profile view.

**Comment by jordanlesich** [comment]
Honestly, a light rebuild of Hub is probably easier. It's one page. Most of the stuff here is not using our libs.

**Comment by jordanlesich** [comment]
No hook yet. But prop drilling is fixed.
