### ISSUE TITLE
Design List/Table System

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#415]
Investigate List/Cards/Query filter system
Blockers:

- Build a system that composes react-table to render a table view quickly
- This system should be able to handle filtering results dynamically
- Should be able to handle sorting dynamically
- Should be able to handle backend search dynamically
- Search, filter, sort are optional

If this system is too complex, build pieces that would work together. 

Example, a hook + table component

**Comment by skuhlmann** [comment]
We have this now.
