### ISSUE TITLE
Baal: Split Shares into new contract

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#42]
- [x] Make contract updates
- [x] Can we get a peer review to help solidify the choice?

**Comment by skuhlmann** [comment]
https://github.com/HausDAO/Baal/tree/feature/sharesToken

**Comment by earth2travis** [comment]
Moloch Mystics are working on a few code changes. Hoping to get it good enough to lock.

**Comment by earth2travis** [comment]
Relates to: https://github.com/HausDAO/daohaus-monorepo/issues/44

**Comment by earth2travis** [comment]
Creating new issues for code updates and deployments

**Comment by earth2travis** [comment]
https://baal-docs.vercel.app/baal-cli

**Comment by skuhlmann** [comment]
Going to close this issue.

We will track the updates Bill is making here:
https://github.com/HausDAO/daohaus-monorepo/issues/56
