### ISSUE TITLE
Remove human-format and human-format related d.ts files across the monorepo

### ISSUE THREAD

**Issue by jordanlesich** [HausDAO/daohaus-monorepo#427]
Our build is having trouble passing along .dts files that we make for libraries that don't have them. 

Here's some background detail on this issue. 

https://discord.com/channels/709210493549674598/951186621397618708/994671750413570058
https://discord.com/channels/709210493549674598/951186621397618708/996820770397372516

In this case, it's human format. 

- Let's remove human-format for now and all the .d.ts files that use it. 
- Then we need to rebuild the readableNumber utils with a better library 
- Then write docs about this and place them where other devs can see. Until we have a good solution to this problem. Let's not try to type libs without d.ts files. 

maybe switch to http://numeraljs.com/

**Comment by brossetti1** [comment]
looking for an early review on this one.
