### ISSUE TITLE
Create MemberCard Component

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#429]
<img width="274" alt="Screen Shot 2022-07-21 at 8 39 03 AM" src="https://user-images.githubusercontent.com/42706432/180215304-3a930d9e-e46c-4f96-bf43-7453e0e608bd.png">

Figma:
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6242%3A136826

## Specs
The member card component consists of a profile image, member name, and a dropdown. This is used throughout the app when a member is referenced. 

When clicking to the dropdown, it shows:

- View profile 
-- If in DAO & member > DAO member profile 
-- If not in DAO or not member > User public profile
- Blockscout/Etherscan/etc link > new tab 
- Copy address

**Comment by adriennetilley** [comment]
specs added, ready to review/dev

**Comment by skuhlmann** [comment]
@adriennetilley 

Can we see what it would look like if the member doesn't have an ens name... also is this ens name or ceramic profile name?

**Comment by adriennetilley** [comment]
Yeah, I'll work on that. This example in my head was the ceramic username. I think anytime a member is listed it should go Ceramic > fallback to ENS > fallback to address - does that make sense or does it feel like ENS trumps all? You may know better than me, I don't even have an ENS (like a peasant)
