### ISSUE TITLE
Write 'DAO Producer Jobs' section

### ISSUE THREAD

**Issue by TravisWyche** [HausDAO/daohaus-monorepo#478]
https://hackmd.io/@daohaus/V3Docs-DAOProducerJob

**Comment by earth2travis** [comment]
https://staging-haus-toolbox.vercel.app/decentralized-infrastructure/jobs#producer-jobs

This section could probably use some elaboration but is good enough for now.

**Comment by earth2travis** [comment]
https://github.com/HausDAO/sdk-docs/pull/34/commits
