### ISSUE TITLE
@daohaus/data: Add polling functionality to queries

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#48]
## Overview

Add the ability to turn on query polling to continually query and return data on an interval.

### Details

Polling function that wraps the query function and:
- provide callback to call and returns data to on interval
- includes an interval

interface should be a new function, maybe:

```
pollQuery(functionName, args, interval, callback)
```

#### Testing
Can be tested with core ui rage app that queries proposals

**Comment by jordanlesich** [comment]
Thinking that this would exist better as a modular utility, exported separately, and perhaps composed by Haus (but not needed, imo)

We need to keep in mind that 
- TXbuilder is going to wrap this call 
- We have 3 lifeCycle methods that we would want to allow callbacks for. (pollSuccess, pollFail, pollTimeout) and perhaps more. 
- We have a test
- We have a fetch
- Typing this has been really tough so far

**Comment by earth2travis** [comment]
Related to DAO context and TX builder
