### ISSUE TITLE
React Version Issues with UI Library

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#484]
## Feature

`npm i @daohaus/ui`

## Expected outcome

Expected the package to install

## Actual outcome

Got some NPM errors (see screenshot)

## Browser

![Image](https://user-images.githubusercontent.com/522182/179862417-f96785bf-c834-4ad5-b36e-6965798c9386.png)

## Screenshots and context

![Image](https://user-images.githubusercontent.com/522182/179862466-106accda-36f7-4e4a-a52e-f9f56810f1d1.png)

**Comment by earth2travis** [comment]
Jord thinks we can solve this by updating the checkbox dependency

**Comment by earth2travis** [comment]
Jord is updating the dependencies. We need to bump the package version on NPM. We also need to discuss updating to React 18 globally.

**Comment by earth2travis** [comment]
@jonathanprozzi has this been resolved?

**Comment by jonathanprozzi** [comment]
This seems to be resolved -- Radix added in support for React 18
