### ISSUE TITLE
Gnosis Safe Summon App: Integrate into monorepo

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#487]
# Details

@santteegt 's gnosis safe app can become another of the apps in the daohaus mono repo.

- new folder in app/ for gnosis-safe-summon-app
- nx commands for serve and deploy
- figure out what is needed for deployment

we should connect with @keating on some of this.

**Comment by santteegt** [comment]
New branch https://github.com/HausDAO/daohaus-monorepo/tree/summon-safe-app
