### ISSUE TITLE
Gnosis Safe Summon App: Add some Daohaus Branding

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#488]
# Details

We want to keep the gnosis styling, but find a way to add a daohaus logo or icon.

Add footer:
![Image](https://user-images.githubusercontent.com/6923345/180062585-1c7869f2-691e-4b3d-93db-15b87959d121.png)

Here are some screenshots of the current app:
https://discord.com/channels/709210493549674598/998651677764747325/999394130323046510

This is the view of the app in the custom app directory - the 1st thing people will see:
![Image](https://user-images.githubusercontent.com/6923345/180067672-4423431c-6298-4d33-bc2c-8134218a7b06.png)

Then these are the screens in the custom app:
![Image](https://user-images.githubusercontent.com/6923345/180067674-e87c6ad4-d1c2-41c1-95b2-868f4784320c.png)
![Image](https://user-images.githubusercontent.com/6923345/180067675-65d01fc1-53c6-4a80-8c6b-f1c13920d8fe.png)
![Image](https://user-images.githubusercontent.com/6923345/180067676-db164cd7-babc-40d4-b0f3-27c057dbbcec.png)
![Image](https://user-images.githubusercontent.com/6923345/180067673-3558d53e-d87b-47a8-9c57-b99453d66957.png)

**Comment by adriennetilley** [comment]
## For app card 
Update Title and subtitle to:
- Title: 'DAOhaus: DAO Launcher'
- Subtitle: 'Upgrade your Safe to a DAO'

Add DAOhaus logo

## In form 
- Change title to: 'DAO Launcher' 
- Add subtitle: 'Upgrade your DAO with a moloch v3 DAO module. Read more about moloch v3 here' < second sentence is a link to the baal documentation

**Comment by adriennetilley** [comment]
Here is a 'built by daohaus' png ready to go. Let me know if just the logo would be better or if you need a different size. Should be around 150px-200px wide at the bottom, with a bit of padding (~30-50px):

![Image](https://user-images.githubusercontent.com/42706432/180830028-1fea7bb0-f26a-4388-b943-4e56e77ca60b.png)

**Comment by adriennetilley** [comment]
Here are 512x512, 192x192, and the svg version of the logo:

![Image](https://user-images.githubusercontent.com/42706432/181341059-1aff6fd3-4f8a-4387-b991-be7bc751121b.png)
![Image](https://user-images.githubusercontent.com/42706432/181341058-f6fcd811-c090-497c-96c1-22b10cb29bdd.png)
![Image](https://user-images.githubusercontent.com/42706432/181341060-ea6ee412-3079-4c72-b2b2-dbc0f6e78895.svg)

**Comment by earth2travis** [comment]
Blocked by https://github.com/HausDAO/daohaus-monorepo/issues/487
