### ISSUE TITLE
@daohaus/commons: Set up Sage Library

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#49]
## Overview

Create utilities library in the sage mono repo.

### Todo

- [x] generate package w/ name: @daohaus/utilities
- [x] see spec/rage repo for folder structure

### resources
https://hackmd.io/wtDwRLeVTsepeDjeiQ0lyg?view

**Comment by jonathanprozzi** [comment]
@skuhlmann Moving this into Done! Won't close them out until our Thursday Dragon Sync but moving it over since the PR is merged!
