### ISSUE TITLE
Gnosis Safe Summon App: Update baal factory address

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#491]
# Details

We now have a new deployment of the baal summoner.

new address:

Factory Contract Address: 0x0C5fd8AAdF995e11E5Ac1CD72139Ee4fd72cDeFC

**Comment by skuhlmann** [comment]
Dependent on this ticket:
https://github.com/HausDAO/daohaus-monorepo/issues/462

**Comment by santteegt** [comment]
Done. The only thing left is to find a way to fetch the ModuleProxyFactory address (used to deploy a Zodiac module like Baal). Zodiac doesn't have an official contract on Goerli yet, so I'm hardcoding the address if not found. For other chains, are we going to use the official proxy factories from `@gnosis.pm/zodiac`?

**Comment by earth2travis** [comment]
Blocked by https://github.com/HausDAO/daohaus-monorepo/issues/487
