### ISSUE TITLE
Update Summon App Headline to remove Baal mention

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#494]
# Detail

Referencing this conversation:
https://discord.com/channels/709210493549674598/850110171267203092/999685507527233626

https://summon.daohaus.fun/

Planning to keep the Baal name under the covers. Can we update this headline to:

'Summon a DAO'

It might also be nice to mention Moloch V3 in the sub headline copy: to something like:

'Visit [Docs](https://summon.daohaus.fun/) for help and to learn more about Moloch V3.'

**Comment by earth2travis** [comment]
On it

**Comment by earth2travis** [comment]
Changed heading and sub

<img width="444" alt="image" src="https://user-images.githubusercontent.com/522182/180279152-fff590fa-8410-4163-abcd-f83071ce2163.png">

We do not have docs yet so we just linked to Spencer's article. Can update once the docs are live

**Comment by jonathanprozzi** [comment]
This is closed by #495
