### ISSUE TITLE
Translate Summoner App User Stories into a Testing Script

### ISSUE THREAD

**Issue by TravisWyche** [HausDAO/daohaus-monorepo#497]
Prep these stories for the next testing sync
https://hackmd.io/@daohaus/UserStories-SummonerAppTesting

**Comment by jonathanprozzi** [comment]
@earth2travis do you think we can/should close this out or should we still work to create a script? Since the majority of our testing is now focusing on Admin, wondering if this is not as relevant as it previously was

**Comment by earth2travis** [comment]
@jonathanprozzi closed
