### ISSUE TITLE
@daohaus/abis: Set up sage library

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#50]
## Overview

Create abis library in the sage mono repo. See rage repo.

### Todo

- [ ] generate package w/ name: @daohaus/abis

### resources
https://github.com/HausDAO/daohaus-rage/tree/master/libs/local-abis

**Comment by skuhlmann** [comment]
https://github.com/HausDAO/daohaus-monorepo/pull/51

**Comment by jonathanprozzi** [comment]
Looks like this can be moved to Done and closed since that PR has now been merged. I definitely need to set up that automation!

@skuhlmann just confirming that we should close this

**Comment by skuhlmann** [comment]
Yep - pr just merged this am!
