### ISSUE TITLE
Finish SubNav Dropdown

### ISSUE THREAD

**Issue by 0xRowdy** [HausDAO/daohaus-monorepo#501]
Implement dropdown for sub navigation bar.

**Comment by earth2travis** [comment]
https://github.com/HausDAO/daohaus-monorepo/pull/502

**Comment by 0xRowdy** [comment]
Have Mobile variant and Dropdown refactor in branch for Create In-app Navigation Component[#254](https://github.com/HausDAO/daohaus-monorepo/issues/254). Help to keep PR smaller and update the references used in apps before refactor.
