### ISSUE TITLE
Create DAO Settings Read Only View

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#505]
# Details

Create view of all read-only DAO settings. **Does not include editing/proposal creation.**

Figma design:
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5376%3A113166

## Design TODO
- [ ] Metadata empty state (name only)
- [ ] Where are we getting tooltip copy from?

## Dev TODO
- [ ] desktop and mobile layouts
- [ ] metadata section (avatar image, name, description, id/address, tags, links)
- [ ] governance settings (voting, grace, offering, quorum, minRetention, sponsor threshold) w/ tooltips
- [ ] token section (loot and share symbol, name, supply, transferability)
- [ ] shaman section (shaman list/table with address and permission level)
- [ ] data empty state
- [ ] reusable helper functions to transform raw data into display state

### Components to use
- Layout
- Card
- DataIndicator
- address display (coming soon)

**Comment by adriennetilley** [comment]
Needs mobile view still, but seems ready enough to get started. The mobile view should be completed in the next day or two.
