### ISSUE TITLE
Sync with Keating - Ceramic and Decen Infra

### ISSUE THREAD

**Issue by TravisWyche** [HausDAO/daohaus-monorepo#516]
- Keating / Ceramic, philosophy of the architectural decisions of DH infra (apps hosted on Skynet as a fully decen service, producer jobs on Digital Ocean and Kubernetes clusters) - TBD
    - If someone wanted to run their own Kubernetes cluster, is that possible and how would it be done?

- Add to Decen Infra:
    - Decen Infra intro (including Digital Ocean)
    - Why we have decided to host out infra on decen stack

Cross reference issues #531, #532, #533

**Comment by earth2travis** [comment]
Here is a link to the notes: https://hackmd.io/nac00IplQFqzHjUv7xm_Rw?view

**Comment by earth2travis** [comment]
Decentralized Infrastructure section updated with notes from the interview
