### ISSUE TITLE
Sync with Jord or Rowdy - UI and Features

### ISSUE THREAD

**Issue by TravisWyche** [HausDAO/daohaus-monorepo#517]
Jord and/or Rowdy - UI + Features
    - Walkthrough Storybook
    - High-level design decisions, philosophy of the architecture
    - How we are approaching the component specs: modularity, composability, flexibility - How "legos" informs our features

- Link Storybook into the UI section [https://storybook.daohaus.fun/]

**Comment by earth2travis** [comment]
Here is the link to the notes: https://hackmd.io/bGpwOXyWQ2-01EnanFbPfQ?view

**Comment by earth2travis** [comment]
https://github.com/HausDAO/daohaus-monorepo/issues/43

**Comment by earth2travis** [comment]
https://github.com/HausDAO/sdk-docs/pull/44
