### ISSUE TITLE
HausThemeProvider

### ISSUE THREAD

**Issue by jordanlesich** [HausDAO/daohaus-monorepo#53]
# <HausThemeProvider />

 Haus Theme Provider is a Single Component Config for the DAOhaus UI library. 
 
 The idea is that a developer can add this one component to the root document of their React application, and it will handle 
 
 - GlobalStyles (this wraps https://github.com/HausDAO/daohaus-rage/issues/48)
 - Text CDN imports
 - Dark theme/ Light theme
 - Toggle dark/light
 - Ability for community devs to add their own color themes
 - Devs should be able to access these themes across their app (Wraps styled-components ThemeProvider).
 - Uses Radix Colors by default

**Comment by jordanlesich** [comment]
# Video Explanation 

For review and possibly docs

https://www.loom.com/share/52d11f3bfab94f60951e9e05407054f0

**Comment by earth2travis** [comment]
Add video to WiKi

**Comment by jonathanprozzi** [comment]
Closed by https://github.com/HausDAO/daohaus-monorepo/pull/55
