### ISSUE TITLE
Write ' Ceremic Node' section

### ISSUE THREAD

**Issue by TravisWyche** [HausDAO/daohaus-monorepo#531]
Info should be sourced from walkthrough with Keating. Video forthcoming.

**Comment by earth2travis** [comment]
https://staging-haus-toolbox.vercel.app/decentralized-infrastructure/ceramic-node

**Comment by earth2travis** [comment]
https://github.com/HausDAO/sdk-docs/pull/34/commits

**Comment by earth2travis** [comment]
https://staging-haus-toolbox.vercel.app/decentralized-infrastructure/helm-charts
