### ISSUE TITLE
Update DH Wallet Button Text for Wrong or Unknown Network

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#535]
### Feature

DAOhaus wallet connect

### Expected outcome

For DAOhaus wallet connect, when you are on a network that is not supported the profile/wallet should say:
- For known networks (i.e. ethereum): '@ethereum' 
- For unknown networks: 'Unknown'

### Actual outcome

The button says 'Wrong Network' until you are on the expected network on on a known network. 

### Browser

Chrome

### Screenshots and context

<img width="581" alt="Screen Shot 2022-07-29 at 7 42 48 AM" src="https://user-images.githubusercontent.com/42706432/181751904-5476e9ef-ca75-4096-9e54-e417f3d47f98.png">

**Comment by earth2travis** [comment]
How does this impact Wallet Connect as a stand-alone package? What is the desired functionality outside of the DAOhaus App? Can we customize this in our apps or should the package be updated?

**Comment by earth2travis** [comment]
If the Network Unavailable comes with DAOhaus Connect then the questions about do not matter. Let's process with adding the network name of the currently connected network under the user name.
