### ISSUE TITLE
Add 'Built by DAOhaus' Logo in All Apps

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#537]
### Feature

hub, all

### Expected outcome

The 'Built by DAOhaus' seen in Summon (including padding) should be on all pages as a standard footer - should be seen in Hub for now. 

### Actual outcome

There is no footer in hub and particularly on mobile, some padding would be nice. 

### Browser

Chrome

### Screenshots and context

<img width="602" alt="Screen Shot 2022-07-29 at 7 55 37 AM" src="https://user-images.githubusercontent.com/42706432/181753488-c0044828-a04e-42bb-8bb5-972420ce5ec2.png">

## Details

To start, we can compare the Footer that is implemented in Summon and turn it into a component that is on all views and then also add this to Hub.

From there if we want to consider adding something like this to the component library we could do it. 

A good starting point is to make sure that we're using it on all the apps and that it looks the same.

**Comment by earth2travis** [comment]
Noticed that the footer in Summon is not a component. We may want to make the footer a component and include it on all view.
