### ISSUE TITLE
Improve Hub Search Usability

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#538]
### Feature

hub

### Expected outcome

When typing a search:
- The search field remains in place and your cursor stays in the field, at the last character your typed until the user actively leaves the field 

Speeding up the debounce was noted as a possible option for development as well. 

### Actual outcome

When using the search, after typing for a second it auto-searches for you. When it does this the search field blinks out and returns, your cursor is no longer in the field.

### Browser

Chrome

### Screenshots and context

<img width="570" alt="Screen Shot 2022-07-29 at 8 01 45 AM" src="https://user-images.githubusercontent.com/42706432/181754318-7f8d0ada-6ac1-4476-b991-325ea300c3d2.png">

**Comment by jordanlesich** [comment]
Sounds like the input component might be unmounting.

**Comment by jordanlesich** [comment]
This doesn't seem to be happening on the rebuild. Will keep an eye on it.
