### ISSUE TITLE
Make Minor Tweaks to Hub UI

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#539]
### Feature

hub

### Expected outcome

Here are a few mobile/general UI tweaks to improve the hub styles:
**1.** Table view, left-align table headers and content in all columns 

**2.** Mobile - with cards, either A) (ideally) increase card length and any content inside that is responsive (something like description text) to full width aside from standard padding or B) center it in the middle 
![MUybgcH](https://user-images.githubusercontent.com/42706432/181754809-b05e30f0-d455-4ee4-baad-1da450e037e1.png)

**3.** Mobile - collapse the filters and sort by to one row on mobile
![aqm9PPq](https://user-images.githubusercontent.com/42706432/181755321-db013e73-8312-4915-a3ec-dbcce7c148f3.png)

 

### Actual outcome

n/a

### Browser

Chrome

**Comment by jonathanprozzi** [comment]
@earth2travis self-assigning this since it relates to the mobile views for the card
