### ISSUE TITLE
Configure Storybook for Sage Repo

### ISSUE THREAD

**Issue by jordanlesich** [HausDAO/daohaus-monorepo#54]
# What 

In the previous iteration of Storybook on the Rage repo, we were able to render off components and manipulate their state using the controls. But Storybook is capable of so much more, and we should take advantage of some of the awesome features it provides. 

Here's a few things that would be great to add into our Sage Storybook. 
- [x] Documentation support
- [x] Global styles and theming (https://github.com/HausDAO/daohaus-monorepo/issues/53) 
- [x] Ability to switch between dark/light mode in the storybook interface

**Comment by jordanlesich** [comment]
Thinking around documentation support: 

After snooping countless storybook and component lib repos, I've noticed a few things: 

1) We could spend all year on documenting things in Storybook. Storybook is very useful, but I can't help but wonder if it hits a point of diminishing returns. 

2) MDX Docs work, but not the way I thought. I thought we could have our canvas as a place to interact with the component, then have the docs panel as place to go further in depth. However the docs panel is just a utility that automatically lists out all the subcomponents with a specific story. In summary, I could not find a way to have a regular story + a MD doc per component. Trying to do both causes a collision error, then neither story ends up rendering. I couldn't find a repo in the showcase that solves this.  

3) We are given a pretty sweet path system that we can use to group the stories. Some obvious groups that come to mind are Atoms/Molecules/Organisms, but also global styles. Monday.com had a cool section for 'Foundations' that I thought would be really helpful. 
 
![Screenshot from 2022-04-17 12-50-53](https://user-images.githubusercontent.com/53406838/163730350-5f474be7-821e-4e24-bcce-3c8fa5d63aec.png)

Conclusion: 

I think there's a way to get 80% of the benefit of storybook while investing 20% of the effort. GitHub's React Primer libary does a pretty decent job of this. 

https://github.com/primer/react

They use the story to separate different states and subcomponents of each atom. Then on the docs page, story book automatically lists them out.

Story code:
https://github.com/primer/react/blob/main/src/Button/Button.stories.tsx
The Story:
https://61a90feace7802003a4d9c45-jtvdedpfdr.chromatic.com/?path=/story/composite-components-button--default-button

There's no MDX. But there's an example of the component, the name of the variant, and most importantly, the ability to see the code we use to achieve this effect. In my mind, this is a great low-overhead way to move forward without getting bogged down in low-impact documentation overhead.

**Comment by jordanlesich** [comment]
Review notes: 

Needed to add a useEffect to help story book toggle the context's theming from the top level. 

There's a slight flicker after every save as storybook switches into darkmode (the default). It's slightly annoying. 

-- Fixed by implementing storybook's background parameters.This ensures that the background is the same color before loading the context.

**Comment by earth2travis** [comment]
Next step: https://github.com/HausDAO/daohaus-monorepo/issues/36

**Comment by jonathanprozzi** [comment]
Closed by https://github.com/HausDAO/daohaus-monorepo/pull/55

Next step is #36 like @earth2travis mentioned above.
