### ISSUE TITLE
Summon: adding decimals to fields can cause form errors

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#541]
### Feature

summon

### Expected outcome

When adding decimals to fields, it should either:
- allow it, ex. New Offering should allow for .01 ETH 
- not allow it, ex. .1 seconds is not an option

### Actual outcome

When adding seconds to some fields as error is thrown that won't go away until you refresh the page. 

### Browser

Chrome

### Screenshots and context

![sPykT37](https://user-images.githubusercontent.com/42706432/181757120-877cac2f-edd9-4815-a0fc-ca5c4d03ab95.png)

**Comment by earth2travis** [comment]
![Image](https://user-images.githubusercontent.com/522182/179835395-c6126ca1-2d7f-43a5-9489-3b6f77cae5ce.png)

![Image](https://user-images.githubusercontent.com/522182/179835427-34da7e05-cdff-4a24-b674-fa5d24c00570.png)
