### ISSUE TITLE
Update Copy When not Connected

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#542]
### Feature

summon

### Expected outcome

Adjust the message 'not connected' error (above summon button) to: 'Connect wallet to summon a DAO.'

### Actual outcome

n/a - see image

### Browser

Chrome

### Screenshots and context

<img width="643" alt="Screen Shot 2022-07-29 at 8 30 27 AM" src="https://user-images.githubusercontent.com/42706432/181761186-6f8453a1-f661-47b2-b655-18fe4cd84798.png">

**Comment by earth2travis** [comment]
Made update in ConnectBox.tsx

**Comment by earth2travis** [comment]
https://github.com/HausDAO/daohaus-monorepo/pull/643
