### ISSUE TITLE
Improve Copy When No DAO Memberships Found

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#544]
### Feature

Exploring Hub as a user who isn't in any DAOs

### Expected outcome

For the copy to not reference the _Explore_ feature

### Actual outcome

The copy is misleading since it says "No DAO memberships found. Connect another wallet or Explore a Million Daos!"

Since we don't have any of the _Explore_ functionality in Alpha we should remove that last sentence entirely and possibly say something like "No DAO memberships found for this address."

### Browser

Brave

### Screenshots and context

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/9438776/181765144-c20b64a5-87bc-4250-b9cc-8c662de06d84.png">

**Comment by earth2travis** [comment]
No DAO memberships found in this wallet

**Comment by earth2travis** [comment]
in `HomeDashboard.tsx`

Changed:

```
  <ParMd>
    No DAO memberships found. Connect another wallet or Explore a Million Daos!
  </ParMd>
```

To: 

```<ParMd>No DAO memberships found in this wallet.</ParMd>```
