### ISSUE TITLE
Make Connected Network Human Readable

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#545]
### Feature

My DAOs list when connected and in DAOs

### Expected outcome

As a user who is connected and a member of at least DAO, I'd like the displayed `network` to be more human readable instead of the `chainId` in both List and Card views

### Actual outcome

The `network` displays as the `chainId` instead of the "human readable" network name that is more familiar.

### Browser

Brave

### Screenshots and context

<img width="393" alt="image" src="https://user-images.githubusercontent.com/9438776/181767636-fa5d9a13-75cc-4b07-851d-c75a21abc5c4.png">

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/9438776/181767679-6b47b7f6-215e-49aa-ab91-a739b157c2f5.png">

## Details

- Likely can map this to our existing keychain object to use the human readable name for each network

**Comment by brossetti1** [comment]
fixed and merged already
