### ISSUE TITLE
Capitalize "Daos" in Hub Search Bar

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#546]
### Feature

Exploring the Hub interface as a connected user

### Expected outcome

As a connected user I'd expect that the search bar placeholder says "Search DAOs" 

### Actual outcome

The search bar placeholder says "Search Daos"

### Browser

Brave

### Screenshots and context

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/9438776/181768177-64865656-7e70-4f7c-a20f-a17f213035b4.png">

**Comment by earth2travis** [comment]
In `SearchInput.tsx`

Change:

`placeholder="Search Daos"`

To:

placeholder="Search DAOs"
