### ISSUE TITLE
Update DAO Card Tag Colors

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#548]
### Feature

Exploring the Hub as a connected user in at least 1 DAO

### Expected outcome

This is working as intended, but it's a minor enhancement -- we can utilize more dynamic colors for our tags (or perhaps different tag colors for different pieces of information)

### Actual outcome

Currently, all of the tags used in the DAO Cards are the same shade of blue and don't have a lot of contrast. We may want to explore how we want to generate tag colors.

### Browser

Brave

### Screenshots and context

<img width="399" alt="image" src="https://user-images.githubusercontent.com/9438776/181770165-3d43200b-7757-4517-8529-95e8354785d1.png">

**Comment by earth2travis** [comment]
@adriennetilley do we want to change the shade of these tags?

**Comment by earth2travis** [comment]
Is the problem that all of the tags are the same color?

The only one that seems to need to draw attention is delegate. Should we create a badge for delegate rather than using a tag?

We also need to refactor the tag component as it is not using our theming system.

**Comment by adriennetilley** [comment]
Sorry for the wait on this!

Let's do the following color updates:
- Network in radix red - bg: dark/3, text: dark/11
- Delegate tag changed to radix amber - bg: dark/amber, text: dark/11
- Contract name in radix indigo (kept the same as now) 
<img width="332" alt="Screen Shot 2022-08-19 at 1 12 13 PM" src="https://user-images.githubusercontent.com/42706432/185672375-292a811f-21e5-4944-93d3-bd2654ecf201.png">
