### ISSUE TITLE
Improve Copy in Profile Drop-down

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#550]
### Feature

Connected user exploring the Hub's Profile feature

### Expected outcome

As a user who is connected to Hub and exploring the Profile feature, I'd expect to know how to edit my Profile and what the process is to do so.

### Actual outcome

Currently we are leveraging Ceramic and self.id for Profile updates, which makes a lot of sense given that our profiles themselves pull from Ceramic, but having the Edit link say "Edit SELF_ID" may be confusing for a user. If they're unaware of what SELF_ID is they may not know that this is how they'd edit their profile, and if they do click on it and go to a separate site (self.id) they may not expect this behavior and wonder if it's legitimate.

Additionally, if we change this to something like "Edit Profile on self.id" we can potentially change the other item to "View Public Profile"

### Browser

Brave

### Screenshots and context

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/9438776/181773938-a84e97d2-f320-4f2d-b96e-e13c818aeded.png">

**Comment by earth2travis** [comment]
- Edit Profile on self.id
- View Public Profile

**Comment by earth2travis** [comment]
Do we need to change the link and text to edit on Lens Protocol?

https://www.lensfrens.xyz/

**Comment by earth2travis** [comment]
It looks like this change has already been made in `Profile.tsx`

![Image](https://user-images.githubusercontent.com/522182/184395269-c7bb7214-93b1-4393-a005-6511c19f0e96.png)

Changed: 

`<StyledParMd>View Public</StyledParMd>`

To:

`<StyledParMd>View Public Profile</StyledParMd>`

**Comment by earth2travis** [comment]
Added: 

`linkType="external"`

to Lens Profile link
