### ISSUE TITLE
Hub: Ensure that the field names for the data are the same for List and Grid views and increase clarity on "Delegate" field on List View

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#552]
### Feature

Exploring Hub as a connected user in at least 1 DAO

### Expected outcome

As a user who has connected to Hub and is in at least 1 DAO, I'd expect that the field names/display names for the DAO data would be the same in List and Card views. 

I'd also like for the "Delegate" field in the List View to more clearly indicate that this is a person that I'm _delegating to_ whereas the "Delegate" tag next to the DAO's name shows that _I_ am a Delegate.

### Actual outcome

Right now the field names are slightly different even though they pull the same information. We'll want to make sure that these match.

Additionally, we should update "Delegate" to "Delegated To" in the List View to increase clarity.

### Browser

Brave

### Screenshots and context

Card View:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9438776/181777199-d04ce627-66c9-4b6e-9b79-689d8fb122e3.png">

List View:

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/9438776/181777234-300d7178-3b95-4d5b-bd4a-a123b0d27e08.png">

| List View        | Card View         |
|------------------|-------------------|
| Vaults           | Vaults (with USD) |
| Power            | Voting Power      |
| n/a              | Contract type     |
| Delegated To     | n/a               |
| Active Proposals | Proposals         |

**Comment by earth2travis** [comment]
## Card View

Change: Delegate
To: Delegated To

Change: Proposals
To: Active Proposals

Change: Voting Power
To: Power

## List View

Change: Vaults 
To: Vaults (USD)

Add tooltip to USD that says, "Estimated values from Gnosis Safe API"

**Comment by earth2travis** [comment]
Verified these are now consistent across views
