### ISSUE TITLE
Create Base Warning Atom and UnlockToken Molecule Components

### ISSUE THREAD

**Issue by jordanlesich** [HausDAO/daohaus-monorepo#572]
### Base UI

- Build the Base Field Alert component (can be named something else) 
- Displays a message (left aligned) and arbitrary element (right aligned)
- Consumes our Haus theme, 
- can display success, warning, error states 

![Image](https://user-images.githubusercontent.com/53406838/182040876-0bf6ca3e-99a3-411d-9a25-435634ee64a1.png)

### Unlock Token Molecule
- Fires Unlock token 
- Composes Base UI

**Comment by earth2travis** [comment]
Jord said this one was built in TributePicker
