### ISSUE TITLE
Adjust Padding on Summon Animation/Icon

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#576]
### Feature

summon

### Expected outcome

Adjust padding on the summon animation/icons once transaction complete to be center aligned. See screenshot, looks off when right aligned. 

### Actual outcome

n/a - see expected. 

### Browser

Chrome

### Screenshots and context

![Screen Shot 2022-07-27 at 11 08](https://user-images.githubusercontent.com/42706432/182145760-94d887a6-cf0b-4693-b8c9-1569f6dd256c.png)

**Comment by earth2travis** [comment]
In `<BlockImageContainer>` component

Changed:
- justify-content: center;
- align-items: center;
