### ISSUE TITLE
Add Secondary Text Color

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#584]
![Image](https://user-images.githubusercontent.com/42706432/182415964-affcc5d2-7f43-4209-949b-e843e7f1222a.png)

The core UI designs utilize a secondary text color, this is optional and used to help guide the eye. 

This is also used in the data indicator component. 

Color:
#8DCEC3
Teal/light/7

**Comment by jordanlesich** [comment]
This will be part of my Unsponsored PR
