### ISSUE TITLE
Create Expand Card Component

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#586]
Ticket for the card expander: 

![Image](https://user-images.githubusercontent.com/42706432/182430621-7c0d9cb4-839f-4a34-9c1d-a12699c3455d.png)

Behavior:
- Show/hide button always in bottom-right side of top card
- Clicking expands out more detailed information below - this content can be anything aside from another top-level card
- Ideally this slide animates downward, then content fades in quickly (~300ms or default) the content

**Comment by adriennetilley** [comment]
Ready for spec

**Comment by earth2travis** [comment]
@alexkeating if you have some spare cycles this week let me know and we can bring this over
