### ISSUE TITLE
Specify Language in Code Blocks

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#591]
Make sure all '```tick tick ticks```' indicate type of code

Find all code blocks site wide and add language after the backticks

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

**Comment by jonathanprozzi** [comment]
@earth2travis this is pretty solid already -- I think we both added this at a few parts in previous PRs. We can close this as done -- audit is complete and nothing is left w/o a language

**Comment by jonathanprozzi** [comment]
reopening with a minor fix
