### ISSUE TITLE
Update Icon on Hub Card

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#596]
From Helle

i noticed a very small thing - on hub, the card view/list view button probably should change its icon depending on whether it says "card" or "list", so with "list" maybe the icon could be the "menu-line" icon

![Image](https://user-images.githubusercontent.com/522182/179835649-a265e075-ec5e-42dd-81f8-957c8ae003e3.png)

![Image](https://user-images.githubusercontent.com/522182/179835695-712b3c38-2c28-4e3c-865c-bdeb04ab197e.png)

i don't have any DAOs showing so i'm not sure how it currently works, but i'm assuming it shows "list view" when cards are being displayed, and vice versa for when the list is displayed, so users know what they can toggle to

REACT/REMIX ICON:

`RiMenuFill`

**Comment by earth2travis** [comment]
@7helles can you please provide a link to the icon in Figma?

**Comment by jordanlesich** [comment]
Let's halt improvements to Hub
