### ISSUE TITLE
Create Common Configurations

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#6]
## What

Align on our common configurations for `eslint` `prettier` and `vscode` so that we all use the same linting settings, and ideally our code lints on save.

## Todo

- Scaffold from `nx` recommended `eslint` and `prettier` configurations
 - Share `.vscode` setup with format on save for linting
- Make sure everyone is able to use these instead of any global settings

**Comment by jonathanprozzi** [comment]
@alexkeating -- I'm happy to help with the documentation piece if we want to add this in the root `README`

**Comment by earth2travis** [comment]
@jonathanprozzi is there any additional details required to get this one ready for dev?

**Comment by jonathanprozzi** [comment]
I think this is no longer relevant

**Comment by earth2travis** [comment]
`eslint` `prettier` and `vscode` are already set up in the monorepo
