### ISSUE TITLE
Summoner Form Rules and Validation

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#60]
## Overview

Create the rules and validation schema for the Summoner Form. This supports other user stories and scenarios so this ticket is lighter on those details.

## Deliverables

- Summoner form hooked up to React Hook Form
- Validation for each field including the following:
  - Required fields
  - Custom validation (such as addresses)
  - Leverage `yup` for other common validations such as strings
- Summoner validation created and integrated

## Detail

- Integrate with React Hook Form and look into leveraging `yup` for validation: https://www.npmjs.com/package/yup
- If needed, can define and add more detail about the custom validation rules required for each field.
- There will be some macros that we don’t to necessarily do right now but we’ll want to be mindful of, such as a Segment/Section
- Talk with Design about the pattern for the disabled state (based on not being connected)
- Drop in a rule into a config file that’s “disable if not connected”
- Build out the app and make it work and then we’ll revisit what we can optimize and refactor Form Builder and Transaction Builder features
  - Can we do this before Core UI? Perhaps we could get 90% there – create the packages -> refactor Summoner -> use in Core UI

**Comment by jordanlesich** [comment]
As an add-on to this, I'm going add the internal display logic each form segment has.
