### ISSUE TITLE
Set Character Limit for DAO Name

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#607]
32 fits without scrolling. But we should probably allow for more and break the DAO name into two lines then decide how many characters we can allow before truncating.

<img width="473" alt="image" src="https://user-images.githubusercontent.com/522182/182963578-18e9a6cc-a45c-4797-b5af-e3e85f88708a.png">

## Details

- Look to the DAO name prop and add truncation to it potentially with a max-width of 32 chars and then have the name wrap if > 32 chars (or whatever makes sense based on the media query)

**Comment by brossetti1** [comment]
@earth2travis is this in the hub app?

just want to check this is not the issue here -- im seeing that these names are already truncated in the hub app

![Image](https://user-images.githubusercontent.com/5998100/186703254-fc9627c1-37c3-4acb-905f-365714fb3669.png)

**Comment by earth2travis** [comment]
@brossetti1 yessir the cards in the Hub app. In the design the name is in the same row with the avatar. And the DAO name breaks into two lines before truncating. 

Should also consider if it is necessary or desirable to set some type of maximum on the DAO name when summoning

**Comment by brossetti1** [comment]
oh i see now - my bad, didnt notice that difference!

**Comment by jordanlesich** [comment]
There's a char limit option in the register options API for reac-hook-form and formBuilder. Will make things pretty convenient.
