### ISSUE TITLE
Handle Errors with Sponsor Threshold and New Offering

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#610]
Entering:

![Image](https://user-images.githubusercontent.com/6923345/192001876-52018474-c1a0-4cdc-99b7-baf6381e5502.png)

Results in:

![Image](https://user-images.githubusercontent.com/6923345/192001892-f5695c41-009a-401f-a986-76353c2cda51.png)

**Comment by earth2travis** [comment]
Is it okay to use numbers in the Stake Tokens symbol?

![Image](https://user-images.githubusercontent.com/522182/182963452-a2f4a46a-f8e3-4df1-9457-a3168bc32ca5.png)

**Comment by earth2travis** [comment]
I think the intention here is that these are validated on each field before pushing submit

**Comment by skuhlmann** [comment]
Looks like there is field level validation on many of these. 

Issue I am still seeing an issue when entering a letter in Sponsore threshold and New offering

**Comment by jordanlesich** [comment]
It's running the unit conversion modifier on non-number values.
