### ISSUE TITLE
Create Voting Bar Component

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#619]
The red/gred/grey voting bar as a component:
![Image](https://user-images.githubusercontent.com/42706432/187204990-e0d42e10-6004-4df6-b73c-bc853c0d1a32.png)

PL Specs:
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6748%3A197271

In context: 
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5981%3A126369

Behavior:
-  ‘Needs Sponsor’ 
    - Indigo/dark/6 (default primary color)
- The voting bar shows (these colors are used only for this component):
    - Total bar grey (#4C5155, slate/dark/8) 
    - This is the total amount of possible votes (voting tokens) 
- Red (#F16A50, tomato/dark/11) 
    - ‘no’ votes token amount porportional to total possible votes
- Green (#95F3D9, mint/dark/10) 
    - ‘yes’ votes token amount porportional to total possible votes

**Comment by skuhlmann** [comment]
@adriennetilley 

what is the button state if the member has voted?

**Comment by adriennetilley** [comment]
Added info on buttons to the proposal card tickets, buttons not included in this ticket. Only the voting atom itself
