### ISSUE TITLE
Proposals: Build Manage/Update Forms for Shamans

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#624]
This ticket covers the 'Manage Shaman' and 'Update Shaman' proposal forms.

### Add Shaman
Designed layout here: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6209%3A134780

### Manage Shaman
Designed layout here: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6216%3A137653

## Proposal Data
Type: Shaman Proposal
Proposal info that will appear on the proposal details: 'This proposal is adding a Shaman with admin permissions to the DAO. Be sure to look at the contract details for more information.'

### Add Shaman Form Fields
- Shaman Proposa (subheader)
- Add a Shaman (h2)
- Learn more about Shamans in our documentation. (instructional text, link goes to https://baal-docs.vercel.app/tools/shaman)
- Basics (should be the same on all proposals:
    - Proposal Name (required, text field)
    - Description (text area)
    - Link (placeholder 'http://', text field)
 - Shaman Address (required, address input validation) 
 - Permission Level (required, dropdown, default to 0 admin level) 
     - 0 - No Permissions
     -  1 - Admin Only
     -  2 - Manager Only
     -  4 - Governance Only
     -  3 - Admin + Manager
      - 5 - Admin + Governance
      - 6 - Manager + Governance
      - 7 - Admin + Manager + Governance 
- Add Expiration - https://github.com/HausDAO/daohaus-monorepo/issues/498
- 'Submit Proposal' > transaction > takes user to proposal list

### Manage Shaman Form Fields
- Shaman Proposa (subheader)
- Manage Shaman (h2)
- Learn more about Shamans in our documentation. (instructional text, link goes to https://baal-docs.vercel.app/tools/shaman)
- Basics (should be the same on all proposals:
    - Proposal Name (required, text field)
    - Description (text area)
    - Link (placeholder 'http://', text field)
- Shaman (disabled, has current shaman address we are adjusting in place)
- New Permission Level (dropdown, same as Permission Level field above, should default to current shaman's permission)
- Shaman's old permission level is: PermissionValue (text)
- Shaman's new permission level is: UserInputForNewLevel (text, updates with dropdown update to previous question
- Add Expiration - https://github.com/HausDAO/daohaus-monorepo/issues/498
- 'Submit Proposal' > transaction > takes user to proposal list

### Transaction details

This will call the baal submitProposal
```
    function submitProposal(
        bytes calldata proposalData,
        uint32 expiration,
        uint256 baalGas,
        string calldata details
    ) 
```
- expiration: timestamp
-baalGas: gwei
- details - is the json detail string
  - include type: 'issueFunding' or something

#### Proposal action data:

also takes and array of addresses and perms
contract: baal
function: setShamans
args:

address[] calldata _shamans,
uint256[] calldata _permissions

**Comment by adriennetilley** [comment]
design done, ready for review
