### ISSUE TITLE
Create GatedCheckbox Component

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#629]
# Details

We need a way to wrap an input as 'Gated' so if a user checks the checkbox they see the form input/area.

Includes:
- checkbox
- takes text for the explaination
- if checked it shows the input - if not it hides it
- takes the input as a prop

TODO: How does this need to play with form builder?
@jordanlesich 

Example usage in the expiration date component:

![Image](https://user-images.githubusercontent.com/6923345/183709284-1adf917f-79fb-4794-95ac-601adcfe37eb.png)

**Comment by jordanlesich** [comment]
Prop is perfect. That way we can define the gate as a lego. 

We should test it to make sure that it works with other registered Inputs.

**Comment by santteegt** [comment]
two questions:

- gated Input should support most of the wrapped input field components (molecules) ? Or should also support atom components?
- Explanation should be a markdown text?
