### ISSUE TITLE
Fix circular dependency issue between common and contract utility libraries

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#640]
# Details

Circular dependency issue when importing common-utilities into contract utilities.

Common utilities should not depend on any other package so we should look to see if it's importing contract-utilities.

Reported here:

https://discord.com/channels/709210493549674598/951186621397618708/1006800638316924938

![Image](https://user-images.githubusercontent.com/6923345/183948718-38649455-e2a2-4ec3-9bf9-58f4950f31e6.png)

**Comment by earth2travis** [comment]
https://github.com/HausDAO/daohaus-monorepo/pull/645
