### ISSUE TITLE
DAOhaus Connect Disconnect Bug

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#662]
### Feature

Using DAOhaus Connect on the Hub

### Expected outcome

When connecting with a certain address and then switching to another address via MetaMask I'd expect that the DAOhaus Connect component would use my new address instead of my previously connected one.

@earth2travis I'm trying to replicate and wondering if this may be fixed? It may need additional replication

### Actual outcome

When connected to Hub via DAOhaus Connect and then disconnecting and connecting with _a different address_ via MetaMask, the user's previously connected address still shows.

### Browser

Brave

**Comment by earth2travis** [comment]
@jonathanprozzi think this is the bug where if you disconnect and refresh it actually re-connects. This leads me to believe it is not actually disconnecting. Recreated the issue in the following Loom video: [DAOhaus Connect Disconnect Bug #662 ](https://www.loom.com/share/5f96928ff8fc47ec867e92c48f179300)

**Comment by jonathanprozzi** [comment]
Got it / yeah that's what it is. I wasnt quite sure but know this came up. Thanks!
