### ISSUE TITLE
Build Issue DAO Tokens Form

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#667]
This ticket covers the 'Issue DAO Tokens' proposal form.

Designed layout here: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5610%3A117636

### Proposal Data
Type: Token Proposal 
Proposal info that will appear on the proposal details: 'This proposal mints or removes tokens for DAO membership. Be sure to look at the contract details for more information.'

### Form Fields
- Token Proposal (subheader)
- Issue DAO Tokens (h2)
- 'Request membership or increased stake in the DAO. Any tribute must be available in your wallet when proposal is executed. ' (instructional text) 
- Basics (should be the same on all proposals: 
    - Proposal Name (required, text field)
    - Description (text area)
    - Link (placeholder 'http://', text field)
- TOKENNAME Tokens Requested (TOKENNAME = voting token name for DAO, text field, numbers only)
    - Info dot: 'These tokens provide voting privilege and membership in the DAO'
- NOVOTETOKENNAME Tokens Requested (NOVOTETOKENNAME = non voting token name for DAO, text field, numbers only)
    - Info dot: 'These tokens provide non-voting, economic membership in the DAO'
- Add Expiration - https://github.com/HausDAO/daohaus-monorepo/issues/498 

### Transaction details

This will call the baal submitProposal
```
    function submitProposal(
        bytes calldata proposalData,
        uint32 expiration,
        uint256 baalGas,
        string calldata details
    ) 
```
- expiration: timestamp
-baalGas: gwei
- details - is the json detail string
  - include type: 'issueFunding' or something

#### Proposal action data:

1 to many actions
- can send an array of addresses to mint/burn for many at once

contract: baal
function: mintShares/mintLoot
args:
-address[] calldata to
-uint256[] calldata amount

**Comment by adriennetilley** [comment]
design work done, ready for review.

**Comment by skuhlmann** [comment]
@adriennetilley should we have a recipient field on this one too so you can make it for someone else?

**Comment by adriennetilley** [comment]
Sorry I missed the Q! Just saw it once it was closed in my email. Seemed like a good idea to add that recipient field, if it didn't get added we can file an improvement later.
