### ISSUE TITLE
Build Swap Tokens for Shares Form

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#668]
This ticket covers the 'Swap Tokens for Shares' proposal form.

Designed layout here: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6710%3A196875

Proposal Data
Type: Token Proposal
Proposal info that will appear on the proposal details: 'This proposal mints or removes tokens for DAO membership. Be sure to look at the contract details for more information.'

Form Fields
- Token Proposal (subheader)
- Swap Tokens for Shares(h2)
- 'Request membership or increased stake in the DAO. Any tribute must be available in your wallet when proposal is executed. ' (instructional text)
- Basics (should be the same on all proposals:
    - Proposal Name (required, text field)
    - Description (text area)
    - Link (placeholder 'http://', text field)
- TOKENNAME Tokens Requested (TOKENNAME = voting token name for DAO, text field, numbers only)
    - Info dot: 'These tokens provide voting privilege and membership in the DAO'
- NOVOTETOKENNAME Tokens Requested (NOVOTETOKENNAME = non voting token name for DAO, text field, numbers only)
    - Info dot: 'These tokens provide non-voting, economic membership in the DAO'
- Tribute Offered 
    - Info text: 'Give tokens to the DAO in exchange for voting or non-voting token shares.'
    - Related components: 
        - https://github.com/HausDAO/daohaus-monorepo/issues/572 
        - https://github.com/HausDAO/daohaus-monorepo/issues/569
- Add Expiration - https://github.com/HausDAO/daohaus-monorepo/issues/498
- 'Submit Proposal' > takes user to proposal list 

### Transaction details

- there is one of these tribute minion contracts per network
- this is not done with the normal proposal args
  - no action data to encode!
  - just a direct transaction to the minion
- sender of this proposal will become the tributor and receive tokens
  - they must approve the tirbuteMinion to spend their tokens before proposal processing

contract: tributeMinion
function: submitTributeProposal
args:

Baal baal,
address token,
uint256 amount,
uint256 shares,
uint256 loot,
uint32 expiration,
string memory details

**Comment by adriennetilley** [comment]
Design done, ready for review.

**Comment by earth2travis** [comment]
- Also need a form to burn loot and replace it with minted shares (promotion)
- What are the other ways to swap loot for shares?
- This can be contextually placed in the app under member management

**Comment by earth2travis** [comment]
If tokens are transferrable a swap makes sense. Let's make this as imperative as possible in this version
