### ISSUE TITLE
Build Issue Funding Form

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#669]
This ticket covers the 'Issue Funding' proposal form.

Designed layout here: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5685%3A197435

### Proposal Data
Type: Funding Proposal
Proposal info that will appear on the proposal details: 'This proposal will transfer funds from the Main Treasury, be sure to look at the contract details for more information.

### Form Fields

- Funding Proposal (subheader)
- Issue Funds (h2)
- 'Ask the DAO for funds.' (instructional text)
- Basics (should be the same on all proposals:
    - Proposal Name (required, text field)
    - Description (text area)
    - Link (placeholder 'http://', text field)
- Recipient (required) - 
    - [See 'Member/Address Switcher' here](https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6120%3A132023) - ability to pass button into that space should be available in component lib 
    - Defaults to member select list
    - Can switch to address input via button
 - Funds requested (required, text field, number amount only + decimal)
     - Info dot: 'Funds are taken from the DAO's Main Treasury vault. If the funds are not available at time of processing, the proposal will fail.'  
     - Switch between available tokens in DAO treasury 
- Add Expiration - https://github.com/HausDAO/daohaus-monorepo/issues/498
- 'Submit Proposal' > takes user to proposal list

### Transaction details

This will call the baal submitProposal
```
    function submitProposal(
        bytes calldata proposalData,
        uint32 expiration,
        uint256 baalGas,
        string calldata details
    ) 
```
- expiration: timestamp
-baalGas: gwei
- details - is the json detail string
  - include type: 'issueFunding' or something

#### Proposal action data:

contract: erc20
function: transfer
args:

address to
unit256 amount

**Comment by adriennetilley** [comment]
Design done, ready for review

**Comment by skuhlmann** [comment]
I am thinking we'll 1st implement the recipient field with a raw address input as we figure out a few things around data availability from the dev side.

@adriennetilley From the design side we do want to figure out how this works if a dao has 100+ members - pagination/infinite scroll somehow?
