### ISSUE TITLE
Build Guildkick Form

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#670]
This is for the 'Guildkick Member' proposal type. 

Designed layout here: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6252%3A137158

### Proposal Data
Type: Guildkick Proposal
Proposal info that will appear on the proposal details: 'This proposal will guildkick a member of the DAO. Be sure to look at the contract details for more information.

### Form Fields

- Guildkick Proposal (subheader) 
- Guildkick Member (h2)
- 'Propose to exchange a member’s voting token balance with non-voting tokens. This will mean they can no longer vote on proposals once passed. (instructional text)
- Basics 
    - Proposal Name (required, text field)
    - Description (text area)
    - Link (placeholder: 'http://', text field
- Member (required) 
    - [See 'Member/Address Switcher' here](https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6120%3A132023) - ability to pass button into that space should be available in component lib
    - Defaults to member select list
    - Can switch to address input via button
- Add Expiration - https://github.com/HausDAO/daohaus-monorepo/issues/498
- 'Submit Proposal' > transaction > takes user to proposal list

### Transaction details

This function will need to convert all user's shares to loot

contract: baal
function: mintLoot
args:
-address[] calldata to
-uint256[] calldata amount

function: burnShares
args:
-address[] calldata from
-uint256[] calldata amount

**Comment by adriennetilley** [comment]
Design done, ready for review

**Comment by skuhlmann** [comment]
@adriennetilley 

this also has the member input - i feel like we need a it more thought around how are we handle this drop down when +1000 members
