### ISSUE TITLE
Build Delegate Feature and Form

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#671]
# Details

Reference this design/discovery ticket:
https://github.com/HausDAO/daohaus-monorepo/issues/206

Figma:
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=2939%3A22133

Uses the modal component.
- 2 alternate headlines 'Add'/'Manage'
    - Add if there is not already a delegate
    - Manage if there is already a delegate
- Accessed from:
  - member list - Delegate to link
  - my profile page - manage delegate link

Delegate to field
- address input
- can pre-populate the field if opened from a member list element
- when managing an existing delegate it can populate with the current delegate address

Member indicator
- if the address is a member, display their avatar/name (if these exist) and member tag
- If not a member, do not display member tag, but return avatar and name from ceramic/ENS if possible

Voting token to delegate
- lists logged in members totalShares balance
- calculates the voting power

Remove delegate button
- populates the address field with the logged in user's address and triggers transaction

### Transaction details

contract: sharesErc20
function: delegate
args:
- delagatee (address that will be the new delegate)

**Comment by 7helles** [comment]
For: "Remove delegate button - populates the address field with the logged in user's address" - I was thinking pressing this button would close to modal and set it to the logged-in user in the background, but we should probably discuss this interaction a little more -- I'm interested in hearing what behavior other people would expect.

For the member indicator, since non-members can also be delegates, should we expand the avatar/input that is returned to be anything that is available through ceramic/ENS for all addresses, including non-members?

**Comment by earth2travis** [comment]
@7helles @brossetti1 and @dekanbro made some updates to the contract last week and may need to discuss the UX with you

**Comment by skuhlmann** [comment]
> @skuhlmann I have a few UX suggestions and would like to know what you think --
> 
> For: "Remove delegate button - populates the address field with the logged in user's address" - I was thinking pressing this button would close to modal and set it to the logged-in user in the background. Perhaps after signing the transaction, a success toast could show with the words "Delegate successfully removed."

I think this makes sense - we can make the click of that button populate the field and trigger the transaction.

> 
> For the member indicator, since non-members can also be delegates, should we expand the avatar/input that is returned to be anything that is available through ceramic/ENS for all addresses, including non-members? This could perhaps be the same behavior as the Member component Adrienne wrote out here https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6242%3A136826

In the delegateOf column? Yeah we can use that member component in those places. FYI we are still working on some data caching solutions for this - so some of them are using address display components for the meantime.

**Comment by adriennetilley** [comment]
I'm moving this to Ready, think it's good to go
