### ISSUE TITLE
Build Rage Quit Feature and Form

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#672]
To be broken out of this design card:

https://github.com/HausDAO/daohaus-monorepo/issues/206

Figma:

https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6808%3A197739 

Ragequit workflow will be a form accessed from the Member Profile page. 

ParMd: "Step 1. Select voting and/or non-voting tokens"
ParXs: "The amount of voting and non-voting tokens selected in step 1 determines the amount of tokens available to ragequit in step 2."

Field - "Voting Tokens (TOKEN NAME)" 
- name of voting token in parenthesis 
- include a Max Amount indicator 
- numbers only, can include decimals
- info icon wording - ‘These tokens provide voting privilege and membership in the DAO’

Field - "Non-Voting Tokens (TOKEN NAME)" 
- name of non-voting token in parenthesis 
- include a Max Amount indicator 
- numbers only, can include decimals
- info icon wording: ‘These tokens provide non-voting, economic membership in the DAO’

horizontal rule

ParMd: "Step 2. Select tokens to ragequit"

Table:
Amounts in the table will update after values in the voting/non-voting token inputs are adjusted - after clicking out of those inputs, trigger refresh of table values

Table Headers:
- checkbox, checked by default
- Token
- Amount
- USD Value (tooltip - needs text about how value is estimate)

Table rows:
- checkboxes, checked by default
- token component - includes token symbol, name, copy icon, and link
- amount to 2 decimal spaces ?
- dollar symbol and amount to 2 decimal spaces ?

Vertical scrollbar to the right of table columns
- on mobile, table may need a horizontal scrollbar depending on breakpoint, but vertical scroll can be removed (uses same scroll as the page).

Load More button
- centered. stays centered on mobile; does not scroll sideways with tokens 
- primary outline button
- can maximize number of tokens that show before loading more - 20 or 30 would both be fine

horizontal rule

Checkbox - "Ragequit to different address (optional)"
- unchecked by default

Field - "Address to send funds"
- address field
- field shows conditionally when the checkbox above it is checked; when unchecked, it hides field. If form is submitted with a value in the field but the field hidden because the checkbox has been unchecked, clear the value and do not send funds to it.
- underneath the field, return ceramic profile avatar and name, or if that's unavailable, ENS info. If address belongs to a member of the DAO, display a "Member" tag

Submit button 
- full-width, primary

### Transaction details

contract: baal
function: ragequit
args:
- to - address the tokens will go to when rage quit
- sharesToBurn - amount in wei
- lootToBurn - amount in wei
- tokens - array of token addresses held in the safe

**Comment by adriennetilley** [comment]
I'm moving this to Ready, think it's good to go

**Comment by earth2travis** [comment]
@skuhlmann add the detail on how we can strip this down for now
