### ISSUE TITLE
Create Typography Components

### ISSUE THREAD

**Issue by jordanlesich** [HausDAO/daohaus-monorepo#68]
# What 

- [x] Build all of the typography elements that are currently in the Figma doc.
- [x] Build as separate components
- [x] Build Mono Variant
- [x] Build Modifier spans, ex <Bold> <Black> <Italic> 
- Build stories that:
   - [x] display all the texts and which components to use
   - [x] give a rundown on how to use modifiers (with examples)

**Comment by jonathanprozzi** [comment]
Closed by #74 🎉
