### ISSUE TITLE
Create New Proposal Modal

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#695]
Figma: 
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5386%3A113974

Specs:

Outer padding: 3rem
Additional left padding for ParMd-Bold and DataSm elements: 1rem (total 4rem, to make room for background hover state)
Vertical padding between hr and text: 2rem
Padding between text: 0.7rem

Make each proposal section clickable, with a hover state (dark/3):
![Image](https://user-images.githubusercontent.com/97971946/186270291-a565cfb7-fa6a-4805-8baa-028f3d1fbf82.png)

![Image](https://user-images.githubusercontent.com/97971946/186270499-9aeefb2c-e1f2-4d10-b25c-3c8556c0399d.png)

H5: "Choose Proposal Type" - left-aligned
close-fill icon - right-aligned

horizontal rule

ParMd-Bold: "Issue DAO Tokens"
DataSm: "Request or send voting or non-voting DAO tokens"
arrow-drop-right icon: vertically centered, right-aligned

horizontal rule

ParMd-Bold: "Swap Tokens for Shares"
DataSm: "Exchange for voting or non-voting tokens"
arrow-drop-right icon: vertically centered, right-aligned

horizontal rule

ParMd-Bold: "Issue Funding"
DataSm: "Request or send funding from the DAO"
arrow-drop-right icon: vertically centered, right-aligned

horizontal rule

ParMd-Bold: "WalletConnect"
DataSm: "Interact with DApps with your DAO wallet"
arrow-drop-right icon: vertically centered, right-aligned

horizontal rule

ParMd-Bold: "Add Shaman"
DataSm: "Add contract to change DAO properties"
arrow-drop-right icon: vertically centered, right-aligned

horizontal rule

ParMd-Bold: "Manage Shaman"
DataSm: "Update permissions on an existing shaman"
arrow-drop-right icon: vertically centered, right-aligned

horizontal rule

ParMd-Bold: "Update Governance Settings"
DataSm: "Update timing and advanced governance"
arrow-drop-right icon: vertically centered, right-aligned

horizontal rule

ParMd-Bold: "Update DAO Token Settings"
DataSm: "Update the transferability of DAO tokens"
arrow-drop-right icon: vertically centered, right-aligned

horizontal rule

Secondary fill button: "Close", right-aligned; on mobile, have button width span the container (minus 30px padding).

**Comment by 7helles** [comment]
@adriennetilley, question about the trigger for going to these forms -- were you intending it to be clicking on the amber arrow specifically, or treating the whole surface area of each proposal section as a ghost button?
