### ISSUE TITLE
Create Vote List Modal

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#698]
# Designs
Figma: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5597%3A117112

![Image](https://user-images.githubusercontent.com/42706432/187203926-abca907a-f631-42f9-9613-38428458b7e3.png)

# Elements

- Title: Proposal Votes (#) < # is members who have voted
- Vote lines:
    - Date/time of vote (in users timezone) 
    - Membercard
    - Vote Y/N 
    - Vote token total 
- Total // Yes (voting token amount) / No (voting token amout) 
- Close button 

# Behavior
- After 6 member votes, the modal start inset scrolling
- Total should always remain visible, only member/voting amounts should scroll

# Data

- need new dao context elements for vote queries
- add to dao-data first
- pagination or fetch all (loop)

**Comment by adriennetilley** [comment]
Designs added, moving to ready
