### ISSUE TITLE
Sharing Profile Link

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#705]
When sharing a profile link from Hub the person who receives the link goes to their own profile.

- Sam shares link with Travis
- Travis brings up Travis' profile

**Comment by jonathanprozzi** [comment]
Will look into this today

**Comment by jonathanprozzi** [comment]
the `useDaoData` hook is grabbing DAO data for the connected user instead of the address in the URL

**Comment by jonathanprozzi** [comment]
Got the DAOs part of this fixed, but noticing that it shows the connected user's Lens profile information instead of the one from the URL. will work on that too @earth2travis but maybe we can run through this today in our sync to see if you can replicate

**Comment by earth2travis** [comment]
member.jsx in core-ui does the same thing

**Comment by skuhlmann** [comment]
@jonathanprozzi Can you push a branc for this and i'll test that issue out?

**Comment by jonathanprozzi** [comment]
@skuhlmann branch is up at fix/hub-public-profile

The DAO list pulls from the `address` being passed in via the query parameters into `useDaoData` but the displayed profile information (Lens) is coming from the user's profile via `Profile` in `useHausConnect` in the `Profile` component

**Comment by skuhlmann** [comment]
Cool. I'm going to take this one and finish it up! Thanks

**Comment by earth2travis** [comment]
Profile page has been removed
