### ISSUE TITLE
Update Baal in subgraph and apps and add gnosis chain

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#707]
baal deploy on gnosis chain

lootSingleton 0x5F8469B83e09f743FD0B030DEE8E1542649A8B31
sharesSingleton 0xbdA0B1a327c171bCF255338E0e1e5D5714115115
baalSingleton 0x40DB5C64b0f4C9B84946Bd3014627C842e8e4731
Transaction Hash: 0x9d17ff742b155b2c0abc8e343397ab1f3fbccde9750fcbb1e5956f1b20d81f29
Factory Contract Address: 0x100Dc22D8C1eeffB9b25bF9A77331a8bb4C32626
https://blockscout.com/xdai/mainnet/address/0x100Dc22D8C1eeffB9b25bF9A77331a8bb4C32626

**Comment by earth2travis** [comment]
Will proceed with this once we get the results from the Hacken audit
