### ISSUE TITLE
Create Cancel Proposal Button in Proposal Details

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#713]
# Design
Figma: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5591%3A120888

<img width="739" alt="Screen Shot 2022-08-29 at 12 53 09 PM" src="https://user-images.githubusercontent.com/42706432/187253335-e11201d4-472b-4290-a00b-a3cafea7bcf6.png">

# Cancel Proposal button
- ONLY DO THIS ON THE DETAILS PAGE
- only show if in voting + user _can_ cancel (must be sponsor) otherwise this button should not appear 
- only can cancel if:
```
       msg.sender == prop.sponsor ||
                sharesToken.getPriorVotes(prop.sponsor, block.timestamp - 1) <
                sponsorThreshold ||
                isGovernor(msg.sender),
```
   - user is the sponsor OR
   - user is a governor shaman
   - sponsor.shares < dao.sponsorThreshold
      - will require another fetch

**Comment by earth2travis** [comment]
@adriennetilley are we able to get the designs done so we can implement this feature this week?

**Comment by adriennetilley** [comment]
Designs done, just a simple button that only appears if you are capable of cancelling.
