### ISSUE TITLE
Implement Member Cards Across Admin

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#725]
# Details

We need to implement the member card component across the admin app.

The component is built:
https://storybook.daohaus.fun/?path=/story/organisms-membercard--member-card-with-name

But the admin app is just using the address indicator at the moment.

The biggest issue with this is that the component relies on fetching the member address profile from dao-data:

```js
const profile = await haus.get({address: memberAddress})

```

To make this more efficient we should start to cache these profiles in the browser localForge storage. We have patterns for this in the txbuilder for storing abis. We can copy this pattern.

See this file:
https://github.com/HausDAO/daohaus-monorepo/blob/develop/libs/tx-builder-feature/src/utils/cache.ts

When trying to display a membercard we can:
1. look in the localForage for the cached profile
2. if not there fetch the profile and cache in local forage

Look at the initABIs function for where it creates the store. We want to use the same localForage but add a new store for profiles.

### Places in admin to put the membercard in:

- [x]  proposal card and details submitted by
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5553%3A117362
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5591%3A120888

- [x] proposal details votes modal
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=8034%3A208150

- [x] proposal history details
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5591%3A121371

- [x] members list
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5365%3A112855

- [ ] member details delegating to indicator
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6037%3A140410

**Comment by earth2travis** [comment]
Need to go through and find all the spots where we need to put this.

Data for member profile is an extra API call that we need to cache.

**Comment by earth2travis** [comment]
Need to make sure to add ENS for wallet addresses

**Comment by earth2travis** [comment]
![Image](https://user-images.githubusercontent.com/522182/195929874-a1096123-6d5a-4893-be47-a88a2947e46c.png)

**Comment by skuhlmann** [comment]
@earth2travis I think the recipient drop downs/field should be a different ticket - I listed all the display sections above.

**Comment by earth2travis** [comment]
@skuhlmann I created https://github.com/HausDAO/daohaus-monorepo/issues/1031 Do we need to have a broader look at how we handle ENS in the apps or align between the member cards and proposal fields?

**Comment by santteegt** [comment]
~`proposal details votes modal` will be covered in #904~

@skuhlmann Member Profile view is not yet implemented. Maybe it's better to create a separate ticket for implementing that and add the member details delegating indicator
