### ISSUE TITLE
Create In Grace Proposal Action

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#731]
# Designs
Figma: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5981%3A126369

![Image](https://user-images.githubusercontent.com/42706432/187197357-8ea71d3d-cfe3-409a-97ce-07b863e42547.png)

# Status

proposal.status === inGrace

# States
- user voted vs not
- passing/failing

# Elements
- indicate when grace ends
- User Voting token amount 
- User Vote yes/no
- Percent of total Yes votes of entire DAO 

## Behavior 
- There is nothing you can interact with in this state

**Comment by adriennetilley** [comment]
Updated to match designs, moving to ready
