### ISSUE TITLE
Create Ready to Process Proposal Action

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#732]
# Designs
Figma: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5981%3A126369

![Image](https://user-images.githubusercontent.com/42706432/187198030-fcae76ea-d441-4d41-a771-74191eeace90.png)

# status

proposal.status === needsProcessing

# elements
- same proposal passing/failing + percent info as Grace
- estimate gas element
  - text/tooltip to diplay proposa.baalGas

## Execute button
- anyone can execute/process

TX:
```
function processProposal(uint32 id, bytes calldata proposalData)
```
- args - proposalproposaId, proposal.proposaData

**Comment by adriennetilley** [comment]
Designs added, moving to ready
