### ISSUE TITLE
Create Completed Proposal Action

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#733]
# Designs 
Figma: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=5981%3A126369

![Image](https://user-images.githubusercontent.com/42706432/187198348-68d7d6b8-9c32-4b73-a008-0c59099f2895.png)

# status

proposal.status === cancelled || failed || actionFalied || expired

# Elements
- voting bar
- Same passed/failed info/percent from Grace/Ready to Process views 
- indicate the above (cancelled, failed, actionFailed, expired)
  - failed can be due to quorum if the dao has quorum set - otherwise its' just more yes than no votes
  - See figma for more examples of the failed designs

**Comment by adriennetilley** [comment]
Design added, moving to ready
