### ISSUE TITLE
Create Infra Guide

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#737]
Need to document everything related our infrastructure

- NX
- Deployments
- Kubernetes
- Skynet

**Comment by earth2travis** [comment]
- How would this integrate into documentation?
- More technical for our internal teams
- Add a page(s) to the [wiki](https://github.com/HausDAO/daohaus-monorepo/wiki)

**Comment by earth2travis** [comment]
What are our biggest pain points?
Should we consider using Webpack instead?

**Comment by earth2travis** [comment]
Here is the video of the walk-though with Keating: https://www.loom.com/share/efa959576fd04e758d2430b0480ba815

**Comment by earth2travis** [comment]
Here are JP's notes: https://hackmd.io/2pa-y-wuTzKm504h6oAcvA

**Comment by earth2travis** [comment]
Here is JP's first draft: https://github.com/HausDAO/daohaus-monorepo/wiki/Infrastructure-Guide

**Comment by jonathanprozzi** [comment]
This is almost done -- will also add the page about how to create a new app/library using our generators. This'll include a checklist/things to look for.

**Comment by jonathanprozzi** [comment]
https://github.com/HausDAO/daohaus-monorepo/wiki/Infrastructure-Guide

@earth2travis This is done -- splitting the app/lib checklist off into it's own page

**Comment by earth2travis** [comment]
@jonathanprozzi looks great. Guess we can close it out once you add the links to the other page(s) you created
