### ISSUE TITLE
Point Docs Site to `toolbox` Subdomain

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#774]
- [x] Configure https://toolbox.daohaus.fun/ subdomain
- [x] Switch the Vercel deployment to use the new DNS

**Comment by earth2travis** [comment]
https://toolbox.daohaus.fun/ is resolving

Need to merge changes from the `develop` into `main`

**Comment by earth2travis** [comment]
@jonathanprozzi

**Comment by jonathanprozzi** [comment]
Merged `develop` into `main` -- will create a new PR into `develop` with my docs updates. This way we'll have the bulk up since it's now resolving @earth2travis

**Comment by jonathanprozzi** [comment]
done! https://toolbox.daohaus.fun/

**Comment by jonathanprozzi** [comment]
This is done!
