### ISSUE TITLE
Complete Docs Punch-Out List

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#775]
- [x] Fully collapse navigation when site loads
- [ ] Fix navigation jumping around around when you click links
- [x] Add index pages so we do not have duplicates and overviews
- [x] Verify dark mode is default (and update the Moloch v3 docs too)

![duplicate](https://user-images.githubusercontent.com/522182/187971554-453061e2-8601-4791-88b0-9a34d5b80552.png)

![overviews](https://user-images.githubusercontent.com/522182/187971666-ea33aa33-e89e-4d7a-8d3f-29f0d5f897b6.png)

**Comment by jonathanprozzi** [comment]
Revisited this again -- Nextra v2 isn't on a stable release and I upgraded to test it. There are a good bit of breaking changes -- we can wait until the minor version bump (which'll resolve this issue).

We can keep this open until then or close out and likely capture this in a larger Nextra v2 refactor ticket @earth2travis

**Comment by jonathanprozzi** [comment]
Yeah. Let's do that since upgrading to a v2 beta broke a lot and is unstable. I'm hoping that they do a minor version bump that includes this fix

**Comment by jonathanprozzi** [comment]
We can close this out since we merged in Plor's PR https://github.com/HausDAO/sdk-docs/pull/47
