### ISSUE TITLE
Component Library DevOps: Package Setup, GitHub Actions, Deploy Target

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#8]
## What

Add the component library to the monorepo and include the basic packages we'll be using (Radix, Stitches).

## Todo

- Create the `components` package in our monorepo with the `@haus/components` namespace
- Add Radix and Stitches as dependencies
- Add any GitHub Actions or deploy targets we know right now (this also may be down the road and would apply to Storybook)
- Note: We can hold off on adding Storybook until our Rage experiments are complete for https://github.com/HausDAO/daohaus-rage/issues/26 and https://github.com/HausDAO/daohaus-rage/issues/22

## Resources

- [Radix UI](https://www.radix-ui.com/docs/primitives/overview/introduction)
- [Stitches](https://stitches.dev/)

**Comment by earth2travis** [comment]
Has this been split into other issues?

**Comment by earth2travis** [comment]
This issue is now redundant with other issues in the Backlog
