### ISSUE TITLE
App Switcher Updates

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#835]
### Feature

App Switcher

### App

- [Admin](https://admin.daohaus.fun)
- [Summon](https://summon.daohaus.fun)
- [Hub](https://hub.daohaus.fun)

### Expected Behavior

1. Core UI should be called "Admin" in the App Switcher drop-down
2. Items in drop-down should contain icons
3. Docs link should point to documentation
4. Drop-downs should be consistent across apps

### Actual Behavior

1. Core UI is called "Core App" in the App Switcher drop-down
2. There are no icon in the drop-down
3. Docs link is pointing to Storybook
4. Admin drop-downs is different than Summon and Hub

### Screenshots and Context

**1**

<img width="708" alt="image" src="https://user-images.githubusercontent.com/522182/190467394-ed7850fc-3e15-4aaf-a4f8-6756ac8cbf4a.png">

**4**

Summon

<img width="643" alt="image" src="https://user-images.githubusercontent.com/522182/190468764-b0165573-e2f8-403f-a568-6812700e0cdc.png">

Hub

<img width="643" alt="image" src="https://user-images.githubusercontent.com/522182/190468876-5a231316-0257-46e3-8ccb-82df591757f7.png">

Admin

<img width="747" alt="image" src="https://user-images.githubusercontent.com/522182/190468938-1ffaef68-6535-444c-b054-9f5775d094cb.png">

**Comment by jordanlesich** [comment]
It can't atm

**Comment by earth2travis** [comment]
If we combine Hub and Admin we may want to remove App Switcher

**Comment by jordanlesich** [comment]
Something to think about for sure. We will be adding workshop soon, if that helps.

**Comment by earth2travis** [comment]
@alexkeating did you make any progress on getting the items in drop-down to contain icons?

**Comment by earth2travis** [comment]
Closing as the feature will be removed in: https://github.com/HausDAO/daohaus-monorepo/issues/863
