### ISSUE TITLE
Members list shouldn't show member entities without shares or loot

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#838]
### Feature

admin app

### App

- [X] [Admin](https://admin.daohaus.fun)
- [ ] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

If a member entity has no shares or no loot they shouldn't be in the list.

We should probably filter out in the subgraph query if possible.

### Actual Behavior

They show up.

### Steps to Reproduce

go to the members page for this dao:

https://admin.daohaus.fun/#/molochv3/0x5/0x0e37683e91349a5ededa160bbb5d59fde6bc201d/members

### Screenshots and Context

![Screenshot from 2022-09-15 14-01-34](https://user-images.githubusercontent.com/6923345/190498171-8d571022-cb01-42d9-8c8b-96b05cfaaabf.png)

**Comment by skuhlmann** [comment]
Going to require an active member flag to add to queries:

shares > 0 || loot > 0 || delegateShares > 0

**Comment by jonathanprozzi** [comment]
Great idea to add to the queries instead of filtering client side @skuhlmann -- do you think there would be any edge cases where someone in a DAO would want/expect to be able to see these inactive members?

**Comment by skuhlmann** [comment]
- Add field to subgraph for activeMember
   - needs to look at loot + shares + delegate shares each time those are updates in the token mappings
- Update default query in core app to use this field {activeMember: true}
- See how that plays with the other sorting/filtering of members
