### ISSUE TITLE
Proposal Forms Do Not Prevent Submitting if Connected to Wrong Network

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#839]
https://admin.daohaus.fun/#/molochv3/0x5/0xb4b1d6151bba8e0d74429c965d601e236e4207bf/new-proposal?formLego=SIGNAL

Was connected to Mainnet and the submit button activated Metamask without informing user they are connected to wrong network

![Image](https://user-images.githubusercontent.com/522182/187525960-46dd14e4-f69f-4371-ac62-89981aa09268.png)

Relates to: https://github.com/HausDAO/daohaus-monorepo/issues/761

May be a duplicate

**Comment by earth2travis** [comment]
This may have been fixed. Let's try to replicate it.

**Comment by skuhlmann** [comment]
This has been fixed.
