### ISSUE TITLE
Hub App Dao Card Button

### ISSUE THREAD

**Issue by 0xRowdy** [HausDAO/daohaus-monorepo#844]
### Feature

Dao List Cards

### App

- [ ] [Admin](https://admin.daohaus.fun)
- [ ] [Summon](https://summon.daohaus.fun)
- [X] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

You should only be ale to click on the button.

### Actual Behavior

The clickable area is the whole width of the card. See screenshot

![Screen Shot 2022-09-14 at 1 03 31 PM](https://user-images.githubusercontent.com/22626267/190713674-68caf68b-2cdf-46e5-9e47-841b67e37ca9.png)

### Steps to Reproduce

1. Go to Hub
2. Authenticate with a wallet
* Must have DAOs listed
4. Hover over DAO Card "Go" Button. Hover and click to the right side of the button.

### Browser

Firefox, Chrome, Brave, Safari

**Comment by jordanlesich** [comment]
I'd say wait for this. I'm thinking we're going to build Hub into admin

**Comment by jordanlesich** [comment]
Made the button fullwidth, as per another card. Fixes this issue.
