### ISSUE TITLE
Remove Holders from Tokens Cards

### ISSUE THREAD

**Issue by 0x4d4n** [HausDAO/daohaus-monorepo#848]
### Feature

Admin

### App

- [X] [Admin](https://admin.daohaus.fun)
- [ ] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

Expected the Token Holders for Voting and Non-Voting(Economic-Loot) tokens to reflect what was used when forming the DAO.

### Actual Behavior

Both Voting and Non-Voting Token Holders show an incorrect value of 5

### Steps to Reproduce

What we did:
Our DAO was formed with 22 members:
19 Members starting with 10 (Staking) 0 (Loot)
3 Members with 5 (Staking) 0 (Loot)

Total Voting Token holders should be 22 (current shows 5)
Total Non-Voting/Economic/Loot should be 0 (current shows 5)

### Browser

Firefox

### Screenshots and Context

![image](https://user-images.githubusercontent.com/111066081/190908238-dd8350ad-8826-4044-b0c0-648223942f2e.png)

![image](https://user-images.githubusercontent.com/111066081/190908294-84790b39-7ee6-443b-95dd-5be8da9c57b9.png)

![image](https://user-images.githubusercontent.com/111066081/190908344-0f2bfecf-ec81-4f42-86e8-bf99badd1395.png)

**Comment by earth2travis** [comment]
We currently do not have a good way to calculate token holders.

**Comment by 7helles** [comment]
![FireShot Capture 034 - DAOhaus v3 – Figma - www figma com](https://user-images.githubusercontent.com/97971946/192041734-397b88bb-80ff-461b-b407-269e10e3547b.png)

My suggested design adjustments after removing the Token Holders column would be to have a two-column layout, move the Supply column so it is inline with where the current third column is, and no longer truncate the token names.

**Comment by jordanlesich** [comment]
Done
