### ISSUE TITLE
Multi-user (simultaneous) metadata overwrite

### ISSUE THREAD

**Issue by 0x4d4n** [HausDAO/daohaus-monorepo#849]
### Feature

Admin settings

### App

- [X] [Admin](https://admin.daohaus.fun)
- [ ] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

Expected settings saved to not be overwritten by another user who was also updating Metadata at the same time from a different device. 

### Actual Behavior

Settings blanked after user who had a window open while I was updating the Metadata submitted changes after my submission not seeing what I had done. 

### Steps to Reproduce

While testing metadata both myself and another user had windows open on our respective devices. 

I made a change to one field and the other individual to a different field. I saved my changes and he saved his. 

When his changes were saved it overwrote/deleted my change because the field I updated was blank in the window he had open and saved.

Potential fix:
Push only updated fields or check for updated data prior to saving changes and present the user with any overlap or a merge resolution option.

**Comment by earth2travis** [comment]
This is a great point. Unfortunately, preventing this is outside of the scope of our current work
