### ISSUE TITLE
Security/reputation management concern - Metadata

### ISSUE THREAD

**Issue by 0x4d4n** [HausDAO/daohaus-monorepo#850]
### Feature

Admin - Metadata

### App

- [X] [Admin](https://admin.daohaus.fun)
- [ ] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

Expected Admin/Metadata to be protected so not all DAO members could make changes without approval

### Actual Behavior

Any DAO mamber can change Metadata settings without approval or any type of notification.

### Steps to Reproduce

As a DAO member navigate to Admin > More > Settings > Metadata > Update Settings > Have fun and make changes

### Screenshots and Context

This could potentially be used by a disgruntled member or someone who just likes to watch the world burn.

Other possible malicious use case: Compromised member wallet used to update the metadata to point to malicious endpoints, Discord servers, etc. for further scamming.

Suggestion - Consider securing Metadata or requiring a proposal to change.

**Comment by earth2travis** [comment]
This is currently working as expected. This may be something we want to change later. One of the only other options is requiring a proposal to change metadata which could be really slow. The other options is requiring a role to access those settings. Please let us know if this continues to be a concern and we may address it at a later date

**Comment by 0x4d4n** [comment]
Thank you for the insight. I think a role would be fantastic and hope to see it get implemented in a future release.

**Comment by earth2travis** [comment]
This could also be a great enhancement with a boost. You could add this functionality with some sort of NFT/Vcred/DID gating
