### ISSUE TITLE
UI/UX Content/Tooltip update - New Offering (ETH) 

### ISSUE THREAD

**Issue by 0x4d4n** [HausDAO/daohaus-monorepo#851]
### Feature

New Offering (ETH)

### App

- [ ] [Admin](https://admin.daohaus.fun)
- [X] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

Expected New Offering to show XDAI or native chain coin instead of ETH

### Actual Behavior

New Offering was shown as New Offering (ETH)

### Steps to Reproduce

1. Launch https://summon.daohaus.fun/
2. Connect wallet to supported network
3. Scroll to New Offering (ETH)

### Screenshots and Context

When summoning and presented with the option to specify “New Offering (ETH)” this would ideally show the appropriate symbol based on the connected network. E.g. “New Offering (XDAI)” for Gnosis network deployments, etc. Showing ETH could be confusing to the end user deploying the DAO.

![image](https://user-images.githubusercontent.com/111066081/190910905-71bf1c6c-5056-4c8a-b45b-080efc2fe330.png)

**Comment by earth2travis** [comment]
Remove the (ETH) and add words to the tooltip saying that offerings must be in the token native to the network

**Comment by santteegt** [comment]
This is how it looks now 

![Image](https://user-images.githubusercontent.com/926341/192632251-abdb62b2-e6d6-42cf-ba67-772e3f67a94f.png)
