### ISSUE TITLE
UI/UX Proposal Offering display

### ISSUE THREAD

**Issue by 0x4d4n** [HausDAO/daohaus-monorepo#852]
### Feature

Admin Proposals GUI

### App

- [X] [Admin](https://admin.daohaus.fun)
- [ ] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

Expected to see accurate human readable number when viewing Proposal Offering

### Actual Behavior

Presented with a misrepresented number in WEI? format 

### Steps to Reproduce

Submit a proposal from a non-member
Have a member view the proposal details via https://admin.daohaus.fun > Proposals > View Details > Click the Down Chevron (Arrow) view Proposal Offering

### Screenshots and Context

The DAO we setup requires 1 XDAI for “New Offering (ETH)”. A proposal was submitted by a non-member and when you view the details of the proposal we are greeted with “Proposal Offering 1000000000000000000 XDAI”

![image](https://user-images.githubusercontent.com/111066081/190911129-2d450a17-98bd-447d-a5c2-0529f64fad93.png)

**Comment by earth2travis** [comment]
Need to to wei this

**Comment by santteegt** [comment]
Already fixed in #899

**Comment by earth2travis** [comment]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/522182/192618021-41469287-34d5-44ee-bb57-4adf9e9900c0.png">

This appears to be working on Goerli. @0x4d4n please let us know if this is still an Issue on Gnosis Chain
