### ISSUE TITLE
After Proposal Form Submit They Do Not Have a Confirmation Page

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#854]
After submitting a proposal on form:

https://admin.daohaus.fun/#/molochv3/0x5/0xb4b1d6151bba8e0d74429c965d601e236e4207bf/new-proposal?formLego=SIGNAL

The page just reloaded with the same information

![Image](https://user-images.githubusercontent.com/522182/187526845-71e760d2-3215-4e40-9e80-699a8015364a.png)

This leads a user to submit the form again or be confused as to whether it worked right. We should add some type of confirmation view

**Comment by jonathanprozzi** [comment]
@earth2travis This is somewhat related to #859

**Comment by earth2travis** [comment]
@jonathanprozzi closing
