### ISSUE TITLE
Update Token Cards on DAO Home View

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#857]
On DAO home view:

https://admin.daohaus.fun/#/molochv3/0x5/0xb4b1d6151bba8e0d74429c965d601e236e4207bf

![Image](https://user-images.githubusercontent.com/522182/187338219-6390c227-946e-4277-bc02-c3d360f2313c.png)

- Update "Swurls" heading two to say "Tokens" (this should also probably be an h2)
- Change "Voting Tokens" label to "Voting"
- Change "Economic Tokens" label to "Non-Voting"
- Change "LOOT" to "Loot"
- Change both instances of "Token Holders" to "Holders"

**Comment by skuhlmann** [comment]
@earth2travis 

figma has a h4
https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6834%3A187038

**Comment by skuhlmann** [comment]
Change "LOOT" to "Loot" 

LOOT comes from the name the contract assigns to the loot token - we sure we want to override that?

**Comment by earth2travis** [comment]
> figma has a h4 https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6834%3A187038

Assuming design labeled that h4 for the size rather than the semantic level in the document. It is just me nit picking and if we are not consistent with it in the rest of the apps it really does not matter

**Comment by earth2travis** [comment]
> LOOT comes from the name the contract assigns to the loot token - we sure we want to override that?

If that is the last it should be fine to leave in uppercase. We should give the Solidity devs a hard time though

**Comment by earth2travis** [comment]
👆👆 @skuhlmann
