### ISSUE TITLE
Add line break in the proposal card voting/grace period time

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#860]
### Feature

Viewing a recently submitted proposal

### App

- [X] [Admin](https://admin.daohaus.fun)
- [ ] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

Functionality is fine, but we may want to add a line break to the card at the _Voting ends in XX seconds_ text. Similarly for the Grace period

### Actual Behavior

The line wraps after the number of seconds

### Steps to Reproduce

1. Create a new proposal
2. View the proposal details while its in both voting and grace periods

### Browser

Brave

### Screenshots and Context

![image](https://user-images.githubusercontent.com/9438776/191065685-f5337fc4-4c7c-4f41-8bd4-f5c59d2ad4f9.png)

**Comment by earth2travis** [comment]
![Image](https://user-images.githubusercontent.com/522182/191627682-5496153c-691c-4f2c-b65c-6496f8c1777d.png)

**Comment by jordanlesich** [comment]
Align-items: start

**Comment by earth2travis** [comment]
Think we may have decided to increase the size of the right div and decrease the size of the text

**Comment by earth2travis** [comment]
@jordanlesich believe this issue was addressed by increasing the width of the right column and decreasing the size of the text

**Comment by jordanlesich** [comment]
See my other comment on the duplicate issue.
