### ISSUE TITLE
Home nav item stays selected even when on different page

### ISSUE THREAD

**Issue by 7helles** [HausDAO/daohaus-monorepo#862]
### Feature

Admin top nav

### App

- [X] [Admin](https://admin.daohaus.fun)
- [ ] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

When navigating from one page to another in Admin, only one page (the current location of the user) should be active/selected.

### Actual Behavior

The navigation bar at the top of Admin looks like "Home" is active even when the user has navigated to another page.

### Steps to Reproduce

1. Go to a DAO Home page, like https://admin.daohaus.fun/#/molochv3/0x64/0x68ee75440c79e6395880ea8009c9307432e5630b
2. Navigate to another page, such as Proposals
3. See how the "Home" nav item is still selected

**Comment by jordanlesich** [comment]
This is related to a bad useLocation pattern in DH Connect.
