### ISSUE TITLE
Remove App Switcher

### ISSUE THREAD

**Issue by 7helles** [HausDAO/daohaus-monorepo#863]
### Feature

App switcher

### App

- [Admin](https://admin.daohaus.fun)
- [Summon](https://summon.daohaus.fun)
- [Hub](https://hub.daohaus.fun)

### Expected Behavior

When navigating using app switcher, the user should be able to switch between Admin, Summoner, and Hub.

### Actual Behavior

The Admin menu item is missing from the app switcher when in Summoner and Hub.

### Steps to Reproduce

1. From any page in Admin, use the app switcher in the top left to navigate to Hub or Summoner
2. See that Admin is missing from the app switcher and now there is apparently no way to get back to Admin

**Comment by skuhlmann** [comment]
@7helles 

There is no landing page for the Admin app - Admin is always scoped to the dao - so not sure where this would take you.

**Comment by earth2travis** [comment]
@7helles going to move this to design to see if you want to consider how this may be improved

**Comment by earth2travis** [comment]
If we combine the Hub and Admin apps we may consider removing the App Switcher all together

**Comment by earth2travis** [comment]
Updated this to remove App Switcher @jordanlesich
