### ISSUE TITLE
Dropdowns in Admin top nav have unexpected interaction design

### ISSUE THREAD

**Issue by 7helles** [HausDAO/daohaus-monorepo#864]
### Feature

Admin top nav

### App

- [X] [Admin](https://admin.daohaus.fun)
- [ ] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

When clicking "Settings" under "More" in the top nav, the dropdown displaying "Settings" should close automatically when the user moves to the new page, and "More" should look active/selected.

### Actual Behavior

When clicking "Settings" under "More" in the top nav, the dropdown continues to stay open until the user clicks somewhere on the page, and "More" does not appear to be active or selected.

**Comment by earth2travis** [comment]
Added this information to: https://github.com/HausDAO/daohaus-monorepo/issues/536
