### ISSUE TITLE
disconnect daodata from UI components

### ISSUE THREAD

**Issue by brossetti1** [HausDAO/daohaus-monorepo#881]
## Remove DaoData from UI components

https://github.com/HausDAO/daohaus-monorepo/blob/master/libs/ui/src/components/organisms/MemberCard/MemberCard.tsx#L9

The UI contains 1 import from `@daohaus/daodata` - removing this unlinks ethers from the UI via ethers-utilities and removes any dependencies coming from `daodata` -- making our UI package alot smaller.

**Comment by earth2travis** [comment]
Do you still plan on finishing this @brossetti1?
