### ISSUE TITLE
Proofread Summoner Tooltips

### ISSUE THREAD

**Issue by adriennetilley** [HausDAO/daohaus-monorepo#89]
Summoner tooltip text: https://docs.google.com/document/d/1vTRR6mtniP8DQHr3G1edX2y3vehqPWx5yDd3Sn8YGmg/edit

**Comment by jordanlesich** [comment]
Hopped on a few weeks late to do some proof-reading. The thing that stood out to me the most is the way we name our DAO tokens. Not very accessible at all. 

I'm going to bring up a thing in Product Decisions and see if we can do better.

**Comment by jonathanprozzi** [comment]
@jordanlesich @adriennetilley @earth2travis -- Are there some recommendations coming out of that doc/product meeting about what we'd want to change or update?

Once we determine the next steps we can update this issue. Thanks!

**Comment by jordanlesich** [comment]
@jonathanprozzi Just seeing this now. There was a big discussion about token names in product-decisions where did anything besides actually make a decision. I think the decision needs to stem from a place of knowing 100% how these tokens work + trying to use a name that actually signifies what people would be using them for, 

Most of the writing here is fine, Besides token names, I made a few small suggestions.

**Comment by jordanlesich** [comment]
Temporarily switched all references to 'execution stake' and 'non-execution stake' to 'voting stake' and 'non-voting stake' in summoner app. Thinking that in 2028, when we finally all align on what we want to call it, we can switch it back ;)

**Comment by jordanlesich** [comment]
Thinking we might need to come up with better names for some of the fields in the Advanced section. Not priority though.

**Comment by skuhlmann** [comment]
Spencer did this and made updates here:

https://github.com/HausDAO/daohaus-monorepo/issues/365

closing
