### ISSUE TITLE
Add line break to all Proposal statuses

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#893]
### Feature

Viewing a recently submitted proposal

### App

- [X] [Admin](https://admin.daohaus.fun)

### Expected Behavior

All of the statuses to be similar -- split them all into 2 lines by default instead of allowing them to wrap.

### Actual Behavior

Each of these wraps differently -- could we force the wrap to always be on 2 lines?

### Steps to Reproduce

1. Create a new proposal
2. View the proposal status (Proposal Ready for Processing, Proposal Failed, Proposal Cancelled)

### Browser

Brave

### Screenshots and Context

![Image](https://user-images.githubusercontent.com/9438776/191996336-613f10f8-e786-4ec8-9954-03ea90e727da.png)

![Image](https://user-images.githubusercontent.com/9438776/191996390-d5fb01ae-abb3-4ac8-9c4e-7cc65c016070.png)

**Comment by jordanlesich** [comment]
Probably better to extend the size of the right hand side of the card as well. Avi is making a ticket for this.

**Comment by earth2travis** [comment]
@jordanlesich believe this issue was addressed by your recommendation to increase the width of the right column

**Comment by jordanlesich** [comment]
Agreed. Let's do a double check in testing and move on.
