### ISSUE TITLE
Proposal Votes Modal Enhancements

### ISSUE THREAD

**Issue by 7helles** [HausDAO/daohaus-monorepo#904]
### Feature

Proposals > Details > Votes modal

### App

- [Admin](https://admin.daohaus.fun)

### Expected Behavior

Filing this issue to keep track of improvements to the proposal votes modal. 

### Actual Behavior

Figma: https://www.figma.com/file/9lCwprCNaoAmUDmiMQpFEA/DAOhaus-v3?node-id=6708%3A196800

The modal is pretty cramped and small even on desktop. Suggested improvements: 
- Increase modal width on desktop (suggested width 650 px) 
- Left-align date and member, right-align vote info
- Add member dropdown component with avatar and name, if available
- Increase padding between votes 
- On mobile, fold vote/vote weight underneath the member info and make the close button full width

### Screenshots and Context

Current modal:
![FireShot Capture 044 - DAOhaus Admin - admin daohaus fun](https://user-images.githubusercontent.com/97971946/192603155-9440f560-cf05-4882-b537-e2c6e1d3dcbc.png)

Design suggestions:

![FireShot Capture 048 - DAOhaus v3 – Figma - www figma com](https://user-images.githubusercontent.com/97971946/192603672-99847886-f48d-4c87-894d-03ae26e69f10.png)

![FireShot Capture 046 - DAOhaus v3 – Figma - www figma com](https://user-images.githubusercontent.com/97971946/192603687-25449944-ae64-4398-8b45-555bfbdd73fd.png)

**Comment by earth2travis** [comment]
We should also make sure the `Proposal Votes (102)` in the headings displays the total number of votes not the number of voters

**Comment by skuhlmann** [comment]
If we get to this one we will eventually be bring in the membercards - but that is in a different ticket that we are still specing out:

https://github.com/HausDAO/daohaus-monorepo/issues/725

**Comment by santteegt** [comment]
@earth2travis the heading should display the total # (yes + no) votes ?

**Comment by earth2travis** [comment]
@santteegt yes. Total number of votes
