### ISSUE TITLE
Expired Proposals Still Need to be Processed

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#909]
### Feature

- Proposals

### App

- [Admin](https://admin.daohaus.fun)

### Expected Behavior

A proposal that required processing should have a process button in the UI

### Actual Behavior

Expired proposals that require processing do not have a process button in the UI

### Steps to Reproduce

- New proposal with expiration
- Vote
- Grace
- Expire

### Browser

Brave

### Screenshots and Context

All three of these proposals failed because the were not processed prior to expiration

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/522182/192900377-cf072139-1ff2-4b27-918a-03c27fe1e7ae.png">

**Comment by earth2travis** [comment]
May relate to: https://github.com/HausDAO/daohaus-monorepo/issues/915
