### ISSUE TITLE
Show Offering on Proposal Cards and Details View

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#916]
### Feature

Proposals

### App

- [Admin](https://admin.daohaus.fun)

### Expected Behavior

If a proposal requires an offering it should be visible on the card and details view

### Actual Behavior

Offering not displayed on the proposal cards and details view

### Steps to Reproduce

1. In a DAO that requires an offering for proposals
2. Create proposal with offering
3. View proposal card and details view

### Browser

Brave

### Screenshots and Context

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/522182/192908634-8cb8b80d-1675-4aee-921d-f414fc19d5d3.png">

<img width="854" alt="image" src="https://user-images.githubusercontent.com/522182/192908666-873892b8-d935-4466-b85c-f50776d76983.png">

**Comment by earth2travis** [comment]
@7helles let's keep this issue scoped to just the Offering. 

Created another issue for the additional updates: https://github.com/HausDAO/daohaus-monorepo/issues/930

**Comment by 7helles** [comment]
My suggestion would be showing the offering on the proposals view and proposal overview card in the following ways, with the intention of the design being that there is room for other additional info that we may wish to add (like Request amount). 

![Image](https://user-images.githubusercontent.com/97971946/193679037-38f2cbad-b715-4db7-9b5a-e00c72dee47e.png)

![Image](https://user-images.githubusercontent.com/97971946/193679047-d9447ee2-c1fd-4af1-9324-014ea78d4ade.png)

**Comment by earth2travis** [comment]
The offering should be displayed on proposal cards and details view and not be visible if there is not an offering
