### ISSUE TITLE
Execute Button in Active State After Proposal Has Been Executed

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#918]
Switched into proposal details view and Execute is available even though it has already been executed.

Do we need polling to refresh the view?

### Feature

Proposals

### App

- [Admin](https://admin.daohaus.fun)

### Expected Behavior

Would expect the state to be executed and the button to be disabled

### Actual Behavior

Execute button is Enabled and the transaction will fail

### Steps to Reproduce

1. Submit proposal
2. Vote
3. Pass
4. Grace Period
5. Execute
6. Switch to Details View
7. Click Execute button
8. Transaction fails

### Browser

Brave

### Screenshots and Context

<img width="824" alt="image" src="https://user-images.githubusercontent.com/522182/193066611-da82aa91-0407-4297-902b-4839ee7db90c.png">

**Comment by skuhlmann** [comment]
This could be 2 different issues:
1. execution action isn't refreshing the proposal data on the details page - this page does it's own fetch so it's not in context - we need to figure out a way for the action components to refresh this single proposal on success

2. polling for that proposal the proposal details page - maybe refresh once every 10 seconds

**Comment by santteegt** [comment]
related #972
