### ISSUE TITLE
[DATA] Ceramic (Basic Profile)

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#92]
## What

This connects with https://github.com/HausDAO/daohaus-monorepo/issues/88

Create the data fetching for the Ceramic Basic Profile needed for the _Connect Wallet_ smart component/feature and add to the data package since we also need these fetches in the Hub App. 

The user stories below demonstrate how the data fetching will be used in the Hub App, although we'd have similar uses in the Summoner and Core UI apps as well.

We had a note that we may want to generalize this into a `getUserData` call that does the following:
- Tries to return Ceramic
- Tries to return ENS

## User Stories

As a user with a Ceramic profile connected to the app on a supported chain, I want to see my Ceramic basic profile data in the connect button and profile so that I know that the app is pulling in my data.

## Scenarios

```gherkin
Feature: User Profile (Connected, with Ceramic Profile and ENS)

Scenario: User has set up a Ceramic Profile and is connected to the Hub with the same address.
    Given that I'm on the Hub App landing page
    And I've connected my wallet
    And I have set up a Ceramic Profile for my connected address
    Then the Header Profile UI displays my Basic Profile info (username, address, avatar, bio, Edit Profile link)
```

```gherkin
Feature: User Profile (Connected, with Ceramic Profile and no ENS)

Scenario: User has connected their wallet, has set up a Ceramic Profile, and is connected to the Hub with the same address but has NOT set up their ENS.
    Given that I'm on the Hub App landing page
    And I have a Ceramic Profile but not an ENS
    Then the Header Profile UI displays a truncated view of my Eth address
```

## Deliverables

- Fetch and return information related to Ceramic's basic profile
-  Return user's Ceramic basic profile data with the fields that we need:
  -  Connect Wallet:
    - Avatar
    - Name
  - Hub App:
    - Avatar
    - Emoji
    - Background Image
    - Name
    - Address
    - Bio/description

**Comment by skuhlmann** [comment]
Convo with ceramic team:
https://discord.com/channels/682786569857662976/875762106245464125/971519976047513630

**Comment by jonathanprozzi** [comment]
Created an issue for the work being done to unblock this: #141

**Comment by skuhlmann** [comment]
This is unblocked by keating! :fire: 

Seeing a failing test I'm looking into it and I'm am going to do some small rework on the class setup and will PR soon!
