### ISSUE TITLE
Further Decode Action Data on GovernanceConfig Proposals

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#942]
# Details

When decoding action data for governance setting update proposals we need to do a 2nd round of decoding so we can display the args in the governance config.

These are encoded in when creating the proposal.

Example:
https://admin.daohaus.fun/#/molochV3/0x5/0x5e0158adb4d5ccf34736aa5e3d25b23ce41c131d/proposals/38

![Image](https://user-images.githubusercontent.com/6923345/195913302-c4ea5c02-e192-4ca6-bc52-dcd45977026e.png)

Contract reference:
https://github.com/HausDAO/Baal/blob/feat/baalZodiac/contracts/Baal.sol#L844 

```
    function setGovernanceConfig(bytes memory _governanceConfig)
        external
        baalOrGovernorOnly
    {
        (
            uint32 voting,
            uint32 grace,
            uint256 newOffering,
            uint256 quorum,
            uint256 sponsor,
            uint256 minRetention
        ) = abi.decode(
                _governanceConfig,
                (uint32, uint32, uint256, uint256, uint256, uint256)
            );
```

**Comment by santteegt** [comment]
@earth2travis this is how it looks now:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/926341/196816672-344bd6ea-e4cd-42c0-a5cd-79d4b67055a0.png">

**Comment by earth2travis** [comment]
@santteegt this is looking good

@skuhlmann what do you think?
