### ISSUE TITLE
Proposal Card Says Failed While in Grace Period

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#955]
### Feature

Proposals

### App

- [Admin](https://admin.daohaus.fun)

### Expected Behavior

Would expect for it to say Proposal Passed

### Actual Behavior

It says Proposal Failed (in Grace Period) on both the proposal card and proposal details view

### Steps to Reproduce

1. Create new proposal to change token settings
2. Vote yes
3. Wait for voting period to end
4. View proposal card
5. View proposal details

### Browser

Brave

### Screenshots and Context

<img width="748" alt="image" src="https://user-images.githubusercontent.com/522182/194605839-e01ec37e-d0fe-492a-ad73-7d0a4806b70d.png">

<img width="748" alt="image" src="https://user-images.githubusercontent.com/522182/194605931-ede92941-c29f-4d6f-880d-eb24adb003c6.png">

<img width="748" alt="image" src="https://user-images.githubusercontent.com/522182/194605975-57719d2c-5d7a-4f5f-a60a-2591833b60ac.png">

**Comment by earth2travis** [comment]
This issue was replicated with an Issue DAO Tokens proposal

![Image](https://user-images.githubusercontent.com/522182/194611796-3e5e17c7-884f-4779-b113-59f165522414.png)

![Image](https://user-images.githubusercontent.com/522182/194611825-bbed115b-80c8-49f5-96a1-f5786d5ce10d.png)

![Image](https://user-images.githubusercontent.com/522182/194611861-fd82e984-d204-4c2c-be1b-0fabd240f347.png)

**Comment by earth2travis** [comment]
DAO: https://admin.daohaus.fun/#/molochv3/0x5/0x5950bd2f55da1568291cdb8996662ab99e94e732

**Comment by skuhlmann** [comment]
![Image](https://user-images.githubusercontent.com/6923345/194955291-961a1ef5-d741-460c-9c2c-5e948cce482c.png)

real failure

**Comment by earth2travis** [comment]
Was not able to replicate it here: 

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/522182/194956389-3fbbf824-522a-44e0-a99a-3179dca5dcfd.png">

**Comment by skuhlmann** [comment]
@earth2travis Me either - where are we stashing tockets we can't repro?

**Comment by earth2travis** [comment]
@skuhlmann 

<img width="870" alt="image" src="https://user-images.githubusercontent.com/522182/194961392-e48610f2-79cb-4fea-ad53-f2f37959fd98.png">
