### ISSUE TITLE
Update Button in Proposal Status on Details Views

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#957]
### Feature

Proposal Details

### App

- [Admin](https://admin.daohaus.fun)

### Expected Behavior

Would expect the button text to be on a single line with more space between the button and text on left

### Actual Behavior

Show Votes is broken onto two lines in the Voting in Progress phase

### Steps to Reproduce

1. Create Issue Tokens proposal
2. Go into voting phase
3. View proposal details

### Screenshots and Context

- Align the button with the top of the heading Voting in Progress
- Do this for all phases (Submitted, Sponsored, Voting, Proposal Completion
- Make sure the Show Votes text does not break onto two lines

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/522182/194669851-cf683a8a-5250-47b7-90d4-12fc916dcce6.png">

**Comment by skuhlmann** [comment]
![Image](https://user-images.githubusercontent.com/6923345/194960166-298e7d88-660e-4628-b471-1a50cfd4b6ca.png)
