### ISSUE TITLE
Guildkick Proposal Failing With Not Enough Gas

### ISSUE THREAD

**Issue by earth2travis** [HausDAO/daohaus-monorepo#959]
### Feature

Proposals

### App

- [Admin](https://admin.daohaus.fun)

### Expected Behavior

Would expect the [proposal](https://admin.daohaus.fun/#/molochV3/0x5/0xf862337cdc9c6144bc2629a2fc3b9c3aa7dc3a46/proposals/3) to execute

### Actual Behavior

The toast comes up saying Success but the [transaction](https://goerli.etherscan.io/tx/0xcbd2374b6745b2eea3c70143bd81a5d0e29a9437dbba2644742b23d7bb68d7f1) is failing

### Steps to Reproduce

1. Create Guild Kick Proposal
2. Vote yes to pass
3. Wait through Grace
4. Try to execute

### Screenshots and Context

[Transaction](https://goerli.etherscan.io/tx/0xcbd2374b6745b2eea3c70143bd81a5d0e29a9437dbba2644742b23d7bb68d7f1)

<img width="1559" alt="image" src="https://user-images.githubusercontent.com/522182/194674880-5b27d1e5-f179-4199-b019-824fa176e37f.png">

**Comment by skuhlmann** [comment]
@santteegt and @earth2travis  can we retest this once now that the gas was bumped up in that that other pr?

i see this has now been executed:
https://admin.daohaus.fun/#/molochV3/0x5/0xf862337cdc9c6144bc2629a2fc3b9c3aa7dc3a46/proposals/3

**Comment by earth2travis** [comment]
@skuhlmann Guildkick proposal seemed to work fine: https://admin.daohaus.fun/#/molochV3/0x5/0x942cd237b22e14e331a6827f578f9868745ce9f4/proposals/5

https://goerli.etherscan.io/tx/0xa74cff13c94f7c37b8d7f1889d9c34fcce4e576010d76d1ee297f1ef68c18034

**Comment by skuhlmann** [comment]
@earth2travis I was able to test one of these as well and it's looking good.

I think we can close it.

**Comment by skuhlmann** [comment]
Fixed by https://github.com/HausDAO/daohaus-monorepo/pull/954
