### ISSUE TITLE
include package dependencies in build

### ISSUE THREAD

**Issue by brossetti1** [HausDAO/daohaus-monorepo#969]
# Problem

our builds do not currently include the package dependencies for a few libraries.

@keating fixed this on his own vite plugin and presented a working example:

https://github.com/HausDAO/daohaus-monorepo/compare/develop...feature/generate-deps - including extension and cleaning up monorepo build
https://github.com/nxext/nx-extensions/pull/801/files - nx extension update

We should bring these changes into the monorepo

# Solution

- [ ] create the executor for the custom packageJson update
- [ ] include changes for vite builds
- [ ] cleanup packageJsons as seen in @keatings `generate-deps` pr

**Comment by earth2travis** [comment]
Addressed with new monorepo
