### ISSUE TITLE
Numbro function do not work in external vite app in published @daohaus/common-utilities package

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#977]
This is the error I'm seeing:
https://github.com/BenjaminVanRyseghem/numbro/issues/403

Not sure if it's with the build or in the vite app ts config.

![Image](https://user-images.githubusercontent.com/6923345/195686805-c16d4140-9e83-49ec-9f95-e1df3b016dd7.png)

**Comment by earth2travis** [comment]
@skuhlmann has this already been fixed?
