### ISSUE TITLE
@daohaus/data: Create HAUS Price Component

### ISSUE THREAD

**Issue by jonathanprozzi** [HausDAO/daohaus-monorepo#98]
## Overview

This adds everything related to the data needed to display token price information (such as used in the HAUS Price Component in the Hub App). 

## Details

- Fetch token price by address
- Fetch user balance (not sure if we want to add this here or in the fetches related to user @skuhlmann)
- We had some notes on the potential structure for this. Here are some that relate to token price data:
  - `getTokenPriceByContractAddress`
  - `getBalanceByAddress`
  - `totalValue` 

## Related Issues

The UI feature issue for this is outlined in #95 

## Deliverables

-Price fetching functions added to our data package
- User balance by address (or this may be in the address fetches instead)

**Comment by jonathanprozzi** [comment]
@alexkeating @skuhlmann 

- the HAUS Price Component  is currently deprioritized for Hub Alpha pending conversations with product strategy

- we could potentially focus on the data and hold on building the UI component for now

**Comment by skuhlmann** [comment]
Removed from design - Archiving
