### ISSUE TITLE
Migrate app hosting off Skynet

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#993]
- new place to host
- update ci

Some things to explore:
- vercel/ipfs
- fleek/ipfs/filecoin
- https://web3extension.com/

@brossetti1 on filecoin w/ ipfs

https://discord.com/channels/709210493549674598/951186621397618708/1032321198345961512

**Comment by earth2travis** [comment]
Hosting moved to Cloudflare Pages
